spring.application.name=Responsables

#Configuracion del puerto en el que se levantara este MicroServicio
server.port=8003

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=VETERINARIA
spring.datasource.password=DANY12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

#Formatea las sentencias SQL en la consola para que se vean mas entendibles y facil de leer 
spring.jpa.properties.hibernate.format_sql=true

#Muestra las sentencias de SQL que ejecuta Hibernate, el cual se veran los Insert, Select, Update, Delete en el log
logging.level.org.hibernate.sql=debug

#Nivel Trance para que el Binder de parametros de Hibernate 
#Muestre en el log los valores concretos que se enlanzan en los parametros de los querys.
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Configuracion para que Hibernate cree las tablas automaticamente cuando inicie la aplicacion
#En este caso se usa 'update' para actualizar el esquema sin perder datos
spring.jpa.hibernate.ddl-auto=update

#Configruacion de eureka---------------------------------------------------------------------------
#Hostname con el que esta instancia se identifica ante EUREKA
eureka.instance.hostname=localhost

#URL de Eureka al que este servidor se registrara
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

