spring.application.name=Tarea

# Configuracion del puerto
server.port=8080

# Configuracion de la base de datos H2
spring.datasource.url=jdbc:h2:mem:testdb

# Configuracion del driver de la base de datos H2
spring.datasource.driverClassName=org.h2.Driver

# Configuracion del dialecto de la base de datos H2 para JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true

# Configuracion de Hibernate para actualizar el esquema de la base de datos automaticamente
spring.jpa.hibernate.ddl-auto=update