spring.application.name=Veterinaria

#Configuracion del puerto en el que se levantara este MicroServicio
server.port=8004

# Configuracionn de la base de datos H2-----------------------------------------------------------

#Aqui indicamos que los datos se guarden en un archivo

#URL de conexion a H2 en modo archivo
#Los dato se guardaran en ./data/demo (persisten en disco, no solo en memoria)
spring.datasource.url=jdbc:h2:file:./data/demo

#Clase driver JDBC que Spring usa para conectarse a H2
spring.datasource.driverClassName=org.h2.Driver

#Usuario que se conectara a la base H2 (por defecto es sa)
spring.datasource.username=sa

#Pasword del usuario H2, lo colocamos basio
spring.datasource.password=

#Dialecto de Hibernate para generar SQL compatible con H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Muestra en consola las sentencias SQL que ejecuta hibernate (UTIL PARA DEBUG)
spring.jpa.show-sql=true

#Hibernate crea/actualiza automaticamente las tablas segun las entidades
#Actualiza es equema sin borrar los datos . 
spring.jpa.hibernate.ddl-auto=update

#Habilita la consola web de h2 para poder entrar con el navegador
spring.h2.console.enabled=true

#Ruta donde esta disponible la consola H2 
spring.h2.console.path=/h2-console

#Configruacion de eureka---------------------------------------------------------------------------
#Hostname con el que esta instancia se identifica ante EUREKA
eureka.instance.hostname=localhost

#URL de Eureka al que este servidor se registrara
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
