spring.application.name=ApiGateway


#Un apigateway o un puerto de entrada, es un componenete escencial en la arquitectura de MS que
#actua como un unico puertpo de entrada hacia las solictudes de los MS. Su funcion es recibir las
#solictudes, redirigilar al MS correcto. procesaro filtros de seguridad, unificar respuestas
#controlar el trafico. 


#puerto del apigateway
server.port=9000

#habilitarlo como eureka client
spring.cloud.service-registry.auto-registration.enabled=true


#configuracion para enrutar los puertos de los MS a mi apigateway

#Tienda
spring.cloud.gateway.server.webmvc.routes[0].id=Tienda
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8005
spring.cloud.gateway.server.webmvc.routes[0].predicates=Path=/tiendas/**

#Proveedor
spring.cloud.gateway.server.webmvc.routes[1].id=Proveedor
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8080
spring.cloud.gateway.server.webmvc.routes[1].predicates=Path=/proveedores/**

#Departamento
spring.cloud.gateway.server.webmvc.routes[2].id=Departamento
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8003
spring.cloud.gateway.server.webmvc.routes[2].predicates=Path=/departamento/**

#Producto
spring.cloud.gateway.server.webmvc.routes[3].id=Producto
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8002
spring.cloud.gateway.server.webmvc.routes[3].predicates=Path=/productos/**
    
#Empleado
spring.cloud.gateway.server.webmvc.routes[4].id=Empleado
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8001
spring.cloud.gateway.server.webmvc.routes[4].predicates=Path=/empleados/**

#Cliente
spring.cloud.gateway.server.webmvc.routes[5].id=Cliente
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8006
spring.cloud.gateway.server.webmvc.routes[5].predicates=Path=/clientes/**



#configruacion de eureka
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

