--BLOQUES ANONIMOS SQL PL/SQL

DECLARE --SE DECLARA VARIABLES, CONSTANTES O CURSORES

LV_NOMBRE NVARCHAR2(50) := 'ALINE';

    BEGIN --LAS INSTRUCCIONES QUE SE EJECUTAN
        DBMS_OUTPUT.PUT_LINE('HOLA '||LV_NOMBRE); --EL DMS_OUTPUT.PUT_LINE ES COMO EL SYSTEM.OUT.PRINTLN

END;
/ --INDICO PARA DECIRLE AL EJECUTOR QUE HASTA AHI ACABA EL CODIGO

--USO DE CICLOS CON BLOQUES PL/SQL

DECLARE 
    LV_VARIABLE NUMBER := 0;
BEGIN 
    LOOP
        DBMS_OUTPUT.PUT_LINE('VALOR: ' || LV_VARIABLE);
        LV_VARIABLE := LV_VARIABLE + 1;
    
        --CONDICION PARA SALIR DE LA VARIABLE
        IF LV_VARIABLE = 11
            THEN EXIT;
        END IF;
    END LOOP;
END;
/

--USO DEL CICLO FOR
BEGIN 
    FOR i IN 1..10
        LOOP
            DBMS_OUTPUT.PUT_LINE('VALOR DE LA VARIABLE: '|| i);
            EXIT WHEN i = 6;
        END LOOP;
END;
/

--USO HILE Y LOOP
DECLARE 
    LV_ITERADOR NUMBER :=1;
BEGIN
    WHILE LV_ITERADOR <=6
        LOOP
            DBMS_OUTPUT.PUT_LINE('VALOR DE ITERADOR CON WHILE ' ||LV_ITERADOR);
            LV_ITERADOR := LV_ITERADOR + 1;
        END LOOP;
END;
/

--USO DE VARIABLES BOOLEANAS
DECLARE
    LV_VALIDADOR BOOLEAN := FALSE;
BEGIN 
    FOR I IN 1..20
        LOOP
            DBMS_OUTPUT.PUT_LINE('VALOR DEL VALIDADOR: '||I);
            IF I = 9 THEN
                LV_VALIDADOR := TRUE;
            END IF;
            EXIT WHEN LV_VALIDADOR;
        END LOOP;
END;
/
            
--EJERCICIOS
--1. CREAR UN BLOQUE ANONIMO PARA MOSTRAR TU NOMBRE, TU CARRERA Y EL ESTADO DONDE VIVES
DECLARE --SE DECLARA VARIABLES, CONSTANTES O CURSORES

LV_NOMBRE NVARCHAR2(50) := 'JORDANY';
LV_CARRERA NVARCHAR2(50) := 'ING.INFORMATICA';
LV_ESTADO NVARCHAR2(50) := 'PUEBLA';

    BEGIN --LAS INSTRUCCIONES QUE SE EJECUTAN
        DBMS_OUTPUT.PUT_LINE('HOLA MI NOMBRES ES '||LV_NOMBRE||'ESTUDIE '||LV_CARRERA||' Y VIVO EN '||LV_ESTADO); --EL DMS_OUTPUT.PUT_LINE ES COMO EL SYSTEM.OUT.PRINTLN

END;
/ --INDICO PARA DECIRLE AL EJECUTOR QUE HASTA AHI ACABA EL CODIGO

--2. CREAR UN BLOQUE QUE IMPRIMA LAS TABLAS DE MUTIPLICAR DEL 1 AL 10
/* TABLA DEL 1
    1 * 1 = 1
*/
DECLARE 
    LV_RESULTADO NUMBER ;
BEGIN
    FOR i IN 1..10
        LOOP
            DBMS_OUTPUT.PUT_LINE('TABLA DEL : ' || i);
            FOR t IN 1..10
                LOOP
                    LV_RESULTADO := i * t;
                    DBMS_OUTPUT.PUT_LINE(i || '*'|| t ||'='|| LV_RESULTADO );
                END LOOP;
                DBMS_OUTPUT.PUT_LINE('-----------------------' );
        END LOOP;
END;
/

--3.CREAR UN BLOQUE QUE IMRPIMA LOS NUMEROS PARES DEL 1 AL 20
DECLARE
    LV_PARES NUMBER :=2;
BEGIN
    WHILE LV_PARES <=20
        LOOP
            DBMS_OUTPUT.PUT_LINE(LV_PARES);
            LV_PARES := LV_PARES + 2;
        END LOOP;
END;
/
            
--4. USAR UN CICLO WHILE PARA IMPRIMIR MUTIPLOS DEL 5 HASTA EL 50
DECLARE
    LV_PARES NUMBER :=5;
BEGIN
    WHILE LV_PARES <=50
        LOOP
            DBMS_OUTPUT.PUT_LINE(LV_PARES);
            LV_PARES := LV_PARES + 5;
        END LOOP;
END;
/  

