--VISTAS O VIEWS: ES UNA CONSULTA ALMACENADA QUE SE GUARDA EN LA BASE DE DATOS (TABLA VIRTUALIZADA)

/*
VENTAJAS:
    1..SIMPLIFICA CONSULTAS: SE GUARDA LA VISTA Y SE PUEDE UDAR CON LLAMARLA CON EL NOMBRE
    2..SEGURIDAD: SE PUEDE DAR PERMISOS DE ACCEDO A LA VISTA, OCULTANDO LOS DATOS DE LAS TABBLAS REALES
    3..REUTILIZACION: SE PUEDE USAR CUANTAS VECES SE REQUIERA
    4..MANTENIMIENTO: SI CAMBIAS LA CONSULTA EN LA VISTA, NO TIENE QUE CAMBIAR TODAS LAS CONSULTAS QUE LA USAN

TIPOS DE VISTAS:
    1..VISTAS COMPLEAS: CREADAD APARTIR DE VARIAS TABLAS CON JOIN 
    2..VISTA SIMPLE: CREADAS SOBRE UNA SOLA TABLA
*/

--EJEMPLO DE UNA VISTA
--MOSTRAR SOLO LAS COMPUTADORAS QUE SU PRECIO SEA MAYOR A 20,000
CREATE OR REPLACE VIEW V_COMPU_CARAS AS
SELECT ID_COMPU, MARCA, MODELO, PRECIO FROM COMPUTADORA
WHERE PRECIO > 20000;

SELECT *FROM COMPUTADORA;
SELECT * FROM V_COMPU_CARAS;

--MOSTRAR LOS MODELOS DE CADA MARCA
CREATE OR REPLACE VIEW V_MODELO_X_MARCA AS
SELECT MARCA, MODELO FROM COMPUTADORA; 

SELECT * FROM V_MODELO_X_MARCA;

--CATEGORIZAR LAS COMPUS POR PRECIO
CREATE OR REPLACE VIEW V_COMPUS_CATEGORIA AS
SELECT MARCA, MODELO, RAM , PROCESADOR, PRECIO,
    CASE
        WHEN PRECIO < 10000 THEN 'ECONOMICO'
        WHEN PRECIO BETWEEN 10000 AND 20000 THEN 'GAMA MEDIA'
        ELSE 'GAMA ALTA'
    END AS CATEGORIA
FROM COMPUTADORA;

SELECT * FROM V_COMPUS_CATEGORIA;
--------------------------------------------------------------------------------------------------------------------------

//EJERCICIO DE LA TABLA DE TRABAJADOR
--1..MUESTRA SOLO EL NOMBRE , AREA Y SALARIO DEL TRABAJADOR
CREATE OR REPLACE VIEW V_TRABAJADOR AS
SELECT NOMBRE, AREA, SALARIO FROM TRABAJADOR

SELECT * FROM V_TRABAJADOR;

--2..MUESTRAS UNICAMENTE LOS TRABAJADORES DE UN AREA(PUEDES ELEGUIR LO QUE QUIERAS)
CREATE OR REPLACE VIEW V_TRABAJADOR_AREA AS
SELECT * FROM TRABAJADOR 
WHERE AREA = 'Sistemas';

SELECT * FROM  V_TRABAJADOR_AREA;

--3..MUESTRA LOS TRABAJADORES MAYORES A 30
CREATE OR REPLACE VIEW V_TRABAJADOR_MAYORES AS
SELECT * FROM TRABAJADOR
WHERE EDAD > 30;

SELECT * FROM V_TRABAJADOR_MAYORES;
SELECT * FROM TRABAJADOR;

--4..MUESTRA UN DETALLE GENERAL DEL TRABAJADOR Y CATEGORIA POR SALARIO (BAJO, MEDIO, ALTO)
CREATE OR REPLACE VIEW V_TRABAJADOR_DETALLE AS
SELECT NOMBRE, APELLIDO, EDAD, CONTACTO, AREA, SALARIO,
    CASE
        WHEN SALARIO > 15000 THEN 'ALTO'
        WHEN SALARIO BETWEEN 12000 AND 15000 THEN 'MEDIO'
        ELSE 'BAJO'
    END AS CATEGORIA
FROM TRABAJADOR;

SELECT * FROM V_TRABAJADOR_DETALLE;













