---CREACION DE UNA ENTIDAD(TABLA) USANDO DDL

CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTOS NVARCHAR2(100)
);

--OPERACIONES DML QUE SE PUEDEN HACER SOBRE MI TABLA 
--CREAR VALORES NUEVOS EN MI TABLA 
INSERT INTO EMPLEADO VALUES(1, 'FERNANDO','GOMEZ',24,'GERENTE GENERAL', 'PRODUCCION');
COMMIT; --CONFIRMAR, POR CADA OPERACION DDL SE OCUPA EL COMMIT, PARA CONFIRMAR EL CAMBIO REALIZADO DENTRO DE MI TABLA
--PODEMOS USAR LA SIMOBOLOGIA DE ARRIBA O F11

SELECT * FROM EMPLEADO;

--METODOS PARA ELIMINAR 

--EJECUTAR UN DDL PARA ELIMINAR LOS REGISTROS
DELETE FROM EMPLEADO;  --ELIMINA SOLAMENTE LOS REGISTROS 

--EJECUTAR UN DML PARA ELIMINAR LA TABLA 
DROP TABLE EMPLEADO -- BORRAR DEL SISTEMA LA TABLA



--USO DE CONSTRAINT COMO LLAVE PRIMARIA

--EJEMPLO 1 DE USO DE PRIMARY KEY 
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100)
);

--EJEMPLO 2 DE USO DE PRIMARY KEY 
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    PRIMARY KEY(ID_EMPLEADO)
);

--EJEMPLO 3 DE USO DE PRIMARY KEY
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    CONSTRAINT EMPLEADO_PK PRIMARY KEY(ID_EMPLEADO)
--PALABRA RESERVADA CONSTRAINT + EL NOMBRE DEL CONSTRAINT  + EL TIPO DE CONSTRAINT + EL CAMPO DE LA TABLA QUE SERA PK
);
