--PROCEDIMIENTO ALMACENADO (SOBRE PROCEDURE) -> COMO BLOQUES PERO CON NOMBRES

        --SIRVE PARA OPTIMIZAR TAREAS REPETITIVAS
        --MEJORA EL RENDIMIENTO
        --REUTILIZACION
        --SEGURIDAD: DAR PERMISOS A CIERTOS USUARIOS PARA EJECUTAR UN PROCEDIMIENTO ALAMCENADOSIN DARLES ACCESO DIRECTO A LAS TABLAS
        --MANTENIMIENTO FACIL
        
--POR QUE USAR PROCEDIMIENTOS ALMACENADOS
        --ESTANDARIZACION: TODAS LAS APLICACIONES LLAMAS AL MISMO PROCEDIMIENTO Y SE GARANTIZA QUE EL CALCULO O ACCION SEA CONCISTENTE
        --MENOS TRAFICO DE RED
        --MODOLARIDAD: EL SISTEMA QUEDA DIVIDIDO EN PIEZAS PEQUEÑAS
         
--CREAR UN PROCEDIMIENTO ALMACENADO QUE NOS AYUDARA A CREAR UN RESPALDO PARA LA TABLA DE COMPUTADORA
--TODO LO EXISTENTE DENTRO DE LA TABLA COMPUTADORA, SERA COPIADO DENTRO DE OTRA

CREATE TABLE COMPUTADORA_PRD(
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(50),
    MODELO NVARCHAR2(50),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(50),
    PRECIO NUMBER,
    CONSTRAINT COMPU_PRD_PK PRIMARY KEY(ID_COMPU)
);

INSERT INTO COMPUTADORA VALUES (1, 'Dell', 'XPS 13', 16, 'Intel i7', 25000);
INSERT INTO COMPUTADORA VALUES (2, 'Apple', 'MacBook Pro', 32, 'M2 Pro', 45000);
INSERT INTO COMPUTADORA VALUES (3, 'HP', 'Pavilion', 8, 'Intel i5', 15000);
INSERT INTO COMPUTADORA VALUES (4, 'Lenovo', 'ThinkPad', 16, 'Intel i7', 22000);
INSERT INTO COMPUTADORA VALUES (5, 'Asus', 'ROG Strix', 32, 'AMD Ryzen 9', 35000);
INSERT INTO COMPUTADORA VALUES (6, 'Acer', 'Aspire 5', 8, 'Intel i3', 12000);
INSERT INTO COMPUTADORA VALUES (7, 'MSI', 'Modern 14', 16, 'Intel i5', 18000);
INSERT INTO COMPUTADORA VALUES (8, 'Dell', 'Inspiron 15', 4, 'Intel i3', 14000);
INSERT INTO COMPUTADORA VALUES (9, 'Apple', 'MacBook Air', 8, 'M1', 20000);
INSERT INTO COMPUTADORA VALUES (10, 'HP', 'Omen', 64, 'Intel i9', 52000);
INSERT INTO COMPUTADORA VALUES (11, 'Lenovo', 'IdeaPad', 12, 'AMD Ryzen 5', 11000);
INSERT INTO COMPUTADORA VALUES (12, 'Asus', 'VivoBook', 12, 'AMD Ryzen 5', 18000);
INSERT INTO COMPUTADORA VALUES (13, 'Acer', 'Nitro 5', 16, 'Intel i5', 22000);
INSERT INTO COMPUTADORA VALUES (14, 'MSI', 'Prestige', 32, 'Intel i7', 28000);
INSERT INTO COMPUTADORA VALUES (15, 'Dell', 'Alienware', 64, 'Intel i9', 65000);
INSERT INTO COMPUTADORA VALUES (16, 'Apple', 'iMac', 16, 'M3', 35000);
INSERT INTO COMPUTADORA VALUES (17, 'HP', 'EliteBook', 16, 'Intel i7', 23000);
INSERT INTO COMPUTADORA VALUES (18, 'Lenovo', 'Yoga', 8, 'Intel i5', 17000);
INSERT INTO COMPUTADORA VALUES (19, 'Asus', 'ZenBook', 16, 'Intel i7', 26000);
INSERT INTO COMPUTADORA VALUES (20, 'Acer', 'Swift 3', 8, 'AMD Ryzen 7', 19000);

SELECT * FROM COMPUTADORA_PRD;
SELECT * FROM COMPUTADORA;
DELETE FROM COMPUTADORA;
--PROCEDIMIENTO ALMACENADO
CREATE OR REPLACE PROCEDURE PR_RESPALDO_COMPUTADORA
IS
--DECLARACION DE VALORES, CONSTANTES O CURSOS
BEGIN
    --INSTRUCCIONES A EJECUTAR
    --LIMPIAR LA TABLA DE COMPUTADORA_PRD CON UNA SENTENCIA DELETE
    DELETE FROM COMPUTADORA_PRD;
    
    --REALIZAR EL RESPALDO DE COMPUTADORA EN COMPUTADORA_PRD CON INSERT INTO SELECT
    INSERT INTO COMPUTADORA_PRD(ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO)
    SELECT ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO FROM COMPUTADORA;

END PR_RESPALDO_COMPUTADORA;
/

--EJECUTAMOS EL PROCEDIMIENTO, ES DECIR HACE UN RESPALDO
EXECUTE PR_RESPALDO_COMPUTADORA;

--CREAMOS UN PROCEDIMIENTO PARA APLICAR UN DESCUENTO A TODAS LAS COMPUTADORA
CREATE OR REPLACE PROCEDURE APLICAR_DESCUENTO(P_DESCUENTO IN NUMBER) -->ESPERA UN DESCUENTASO
IS
BEGIN 
    UPDATE COMPUTADORA
    SET PRECIO = PRECIO - (PRECIO * (P_DESCUENTO /100));
    --> PODEMOS COLOCAR EL COMMIT AQUI PERO YA NO PODRIAMOS HACER UN ROLLBACK
EXCEPTION
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('ERROR EN EL DESCUENTO: '||SQLERRM);
END APLICAR_DESCUENTO;
/

SELECT * FROM COMPUTADORA;

--EJECUTAMOS EL DESCUENTASO DEL PRODECIMIENTO
EXECUTE APLICAR_DESCUENTO(10) --> AQUI PASAMOS EL PARAMETRO PARA EL DESCUENTASO

--SI NOS EQUIVOCAMOS A APLICAR EL DESCUENTO Y SI NO HICIMOS COMIT ENTONTES PODEMOS HACER UN ROLLBACK PARA REGRESAR LOS VALORES
ROLLBACK;

COMMIT; --CONFIRMAMOS PERO YA NO PODRIAMOS HACER UN ROLLBACK, ALMENOS QUE AGAMOS OTROS PROCEDURE QUE LE AUMENTE LO QUE SE LE DESCONTO








--HACER EL RESPALDO DE ALMACENAMIENTO PARA LA TABLA DE ESTUDIANTE
SELECT * FROM ESTUDIANTE;

--CREAMOS LA TABLA PARA ALMACENAR EL RESPALDO
CREATE TABLE ESTUDIANTE_PRD(
    ID_ESTUDIANTE NUMBER,
    NOMBRE NVARCHAR2(50),
    APELLIDO NVARCHAR2(50),
    EDAD NUMBER,
    CARRERA NVARCHAR2(50),
    SEMESTRE NUMBER,
    AÑO_INGRESO NUMBER,
    CONSTRAINT ESTU_PRD_PK PRIMARY KEY(ID_ESTUDIANTE)
);

INSERT INTO ESTUDIANTE VALUES (1, 'Carlos', 'González', 20, 'Ingeniería en Sistemas', 4, 2023);
INSERT INTO ESTUDIANTE VALUES (2, 'María', 'López', 19, 'Ingeniería Industrial', 3, 2024);
INSERT INTO ESTUDIANTE VALUES (3, 'Juan', 'Martínez', 22, 'Ingeniería Civil', 6, 2022);
INSERT INTO ESTUDIANTE VALUES (4, 'Ana', 'Rodríguez', 21, 'Arquitectura', 5, 2022);
INSERT INTO ESTUDIANTE VALUES (5, 'Luis', 'Hernández', 20, 'Ingeniería Mecánica', 4, 2023);
INSERT INTO ESTUDIANTE VALUES (6, 'Sofía', 'García', 18, 'Licenciatura en Administración', 2, 2024);
INSERT INTO ESTUDIANTE VALUES (7, 'Diego', 'Pérez', 23, 'Ingeniería Electrónica', 7, 2021);
INSERT INTO ESTUDIANTE VALUES (8, 'Valentina', 'Sánchez', 19, 'Diseño Gráfico', 3, 2024);
INSERT INTO ESTUDIANTE VALUES (9, 'Miguel', 'Ramírez', 21, 'Ingeniería en Sistemas', 5, 2022);
INSERT INTO ESTUDIANTE VALUES (10, 'Camila', 'Torres', 20, 'Contaduría Pública', 4, 2023);
INSERT INTO ESTUDIANTE VALUES (11, 'Jorge', 'Flores', 22, 'Ingeniería Química', 6, 2022);
INSERT INTO ESTUDIANTE VALUES (12, 'Isabella', 'Morales', 19, 'Mercadotecnia', 3, 2024);
INSERT INTO ESTUDIANTE VALUES (13, 'Ricardo', 'Vargas', 24, 'Derecho', 8, 2021);
INSERT INTO ESTUDIANTE VALUES (14, 'Fernanda', 'Castro', 18, 'Psicología', 2, 2024);
INSERT INTO ESTUDIANTE VALUES (15, 'Pablo', 'Jiménez', 21, 'Ingeniería en Sistemas', 5, 2022);

--PROCEDIMIENTO ALMACENADO
CREATE OR REPLACE PROCEDURE PR_RESPALDO_ESTUDIANTE
IS
--DECLARACION DE VALORES, CONSTANTES O CURSOS
BEGIN
    --INSTRUCCIONES A EJECUTAR
    --LIMPIAR LA TABLA DE COMPUTADORA_PRD CON UNA SENTENCIA DELETE
    DELETE FROM ESTUDIANTE_PRD;
    
    --REALIZAR EL RESPALDO DE COMPUTADORA EN COMPUTADORA_PRD CON INSERT INTO SELECT
    INSERT INTO ESTUDIANTE_PRD(ID_ESTUDIANTE, NOMBRE, APELLIDO, EDAD, CARRERA, SEMESTRE, AÑO_INGRESO)
    SELECT ID_ESTUDIANTE, NOMBRE, APELLIDO, EDAD, CARRERA, SEMESTRE, AÑO_INGRESO FROM ESTUDIANTE;

END PR_RESPALDO_ESTUDIANTE;
/

--EJECUTAMOS EL PROCEDIMIENTO, ES DECIR HACE UN RESPALDO
EXECUTE PR_RESPALDO_ESTUDIANTE;

SELECT * FROM ESTUDIANTE;
SELECT *FROM ESTUDIANTE_PRD;

DELETE FROM ESTUDIANTE;
DELETE FROM ESTUDIANTE_PRD;


    