/*
TRIGGER

SIRVE PARA:
    -REGISTRAR AUDITORIAS
    -VALIDAD REGLAS DE NEGOCIOS COMPLEJAS
    -MANTENER INTEGRIDAD DE DATOS
    -GENERAR VALORES AUTOMATICOS

TIPOS DE TRIGGER:
    -BEFORE:SE EJECUTA ANTES DE QUE OCURRA UN X EVENTO
    -AFTER: SE EJECUTA DESPUES DE QUE OCURRA UN X EVENTO
    -INSTEAD: SE USA EN VISTAS, REEMPLAZA LA OPERACION DML

NOVEL DE TRIGER:
    -ROW(POR FILA): SE ACTIVA POR CADA FILA AFECTADA
    -STATEMENT(POR SENTENCIAS): SE ACTIVA UNA SOLA VES POR INSTRUCCION SQL, SIN IMPORTAR CUANTAS FILAS SE AFECEN
    
VARIABLES ESPECIALES:
    -OLD: REPRESENTA LOS VALORES ANTERIORES (ANTES DE MODIFICAR)
    -NEW: REPRESENTAN LOS VALORES NUEVOS (DESPUES DE INSERTAR O MODIFICAR)
    NOTA -> ESTOS SOLO FUNCIONAN CON TRIGGER FOR EACH ROW
*/

--CREACION DE UN TRIGER AFTER A NIVEL FILA PARA CREAR UNA AUDITORIA SOBRE UNA TABLA
CREATE TABLE COMPUTADORA(
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(50),
    MODELO NVARCHAR2(50),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(50),
    PRECIO NUMBER,
    CONSTRAINT COMPU_PK PRIMARY KEY(ID_COMPU)
);



--CREACION DE LA TABLA QUE SERA LA BITACORA DE REGISTRO DE MOVIMIENTOS DML
CREATE TABLE BITACORA(
    ID_BITACORA NUMBER,
    
    --VALORES NUEVOS :NEW
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(50),
    MODELO NVARCHAR2(50),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(50),
    PRECIO NUMBER,
    
    --VALORES VIEJOS :OLD
    MARCA_OLD NVARCHAR2(50),
    MODELO_OLD NVARCHAR2(50),
    RAM_OLD NUMBER,
    PROCESADOR_OLD NVARCHAR2(50),
    PRECIO_OLD NUMBER,
    
    --CAMPOS DE CONTROL
    USUARIO NVARCHAR2(50),
    FECHA_NOW DATE,
    MOVIMIENTIO NVARCHAR2(50),
    CONSTRAINT BITACORA_PK PRIMARY KEY(ID_BITACORA)
);

--CREACION DE TRIGGER
CREATE OR REPLACE TRIGGER TR_I_COMPUTADORA
AFTER INSERT ON COMPUTADORA --TIPO DE TRIGGER QUE ACTUA DESPUES DE UN MOVIMIENTO SOBRE LA TABLA
FOR EACH ROW --ACTUARA POR CADA FILA AFECTADA
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(50);
    LV_FHECA DATE;
BEGIN
    --RECUPERAR UN ID VALIDO, LA FECHA DEL SISTEMA Y EL USUARIO DEL SISTEMA
    SELECT NVL(MAX(ID_BITACORA),0) + 1 INTO LV_ID_BIT FROM BITACORA; --NVL ES PARA VALIDAD VALORES NULOS (USA AUTOINCREMENTO)
    SELECT SYSDATE INTO LV_FHECA FROM DUAL;
    SELECT USER INTO LV_USUARIO FROM DUAL;
    
    INSERT INTO BITACORA(ID_BITACORA, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD,
                        PRECIO_OLD, USUARIO, FECHA_NOW, MOVIMIENTIO)
    VALUES(LV_ID_BIT,:NEW.ID_COMPU,:NEW.MARCA, :NEW.MODELO, :NEW.RAM, :NEW.PROCESADOR, :NEW.PRECIO, NULL, NULL,0, NULL, 0,
            LV_USUARIO, LV_FHECA, 'INSERT' );

END TR_I_COMPUTADORA;
/

SELECT * FROM COMPUTADORA;
SELECT * FROM BITACORA;
                        
INSERT INTO COMPUTADORA VALUES (1, 'DEL', 'INSPIRON', 16, 'INTEL CORE i7 9th', 800);

--TRIGGER PARA EDITAR
CREATE OR REPLACE TRIGGER TR_U_COMPUTADORA
AFTER UPDATE ON COMPUTADORA --TIPO DE TRIGGER QUE ACTUA DESPUES DE UN MOVIMIENTO SOBRE LA TABLA
FOR EACH ROW --ACTUARA POR CADA FILA AFECTADA
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(50);
    LV_FHECA DATE;
BEGIN
    --RECUPERAR UN ID VALIDO, LA FECHA DEL SISTEMA Y EL USUARIO DEL SISTEMA
    SELECT NVL(MAX(ID_BITACORA),0) + 1 INTO LV_ID_BIT FROM BITACORA; --NVL ES PARA VALIDAD VALORES NULOS (USA AUTOINCREMENTO)
    SELECT SYSDATE INTO LV_FHECA FROM DUAL;
    SELECT USER INTO LV_USUARIO FROM DUAL;
    
    INSERT INTO BITACORA(ID_BITACORA, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD,
                        PRECIO_OLD, USUARIO, FECHA_NOW, MOVIMIENTIO)
    VALUES(LV_ID_BIT,:NEW.ID_COMPU, :NEW.MARCA, :NEW.MODELO, :NEW.RAM, :NEW.PROCESADOR, :NEW.PRECIO, 
                    :OLD.MARCA, :OLD.MODELO, :OLD.RAM, :OLD.PROCESADOR , :OLD.PRECIO, LV_USUARIO, LV_FHECA, 'UPDATE' );

END TR_U_COMPUTADORA;
/

SELECT * FROM COMPUTADORA;
SELECT * FROM BITACORA;
--ACTUALIZAMOS
UPDATE COMPUTADORA SET 
    MARCA = 'HP'
WHERE ID_COMPU = 1;

--TRIGGER PARA ELIMINAR
CREATE OR REPLACE TRIGGER TR_D_COMPUTADORA
AFTER DELETE ON COMPUTADORA --TIPO DE TRIGGER QUE ACTUA DESPUES DE UN MOVIMIENTO SOBRE LA TABLA
FOR EACH ROW --ACTUARA POR CADA FILA AFECTADA
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(50);
    LV_FHECA DATE;
BEGIN
    --RECUPERAR UN ID VALIDO, LA FECHA DEL SISTEMA Y EL USUARIO DEL SISTEMA
    SELECT NVL(MAX(ID_BITACORA),0) + 1 INTO LV_ID_BIT FROM BITACORA; --NVL ES PARA VALIDAD VALORES NULOS (USA AUTOINCREMENTO)
    SELECT SYSDATE INTO LV_FHECA FROM DUAL;
    SELECT USER INTO LV_USUARIO FROM DUAL;
    
    INSERT INTO BITACORA(ID_BITACORA, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD,
                        PRECIO_OLD, USUARIO, FECHA_NOW, MOVIMIENTIO)
    VALUES(LV_ID_BIT,0, NULL, NULL,0, NULL, NULL, :OLD.MARCA, :OLD.MODELO, :OLD.RAM, :OLD.PROCESADOR , :OLD.PRECIO,
            LV_USUARIO, LV_FHECA, 'DELETE' );

END TR_D_COMPUTADORA;
/

SELECT * FROM COMPUTADORA;
SELECT * FROM BITACORA;
--ELIMINAMOS
DELETE COMPUTADORA WHERE ID_COMPU = 1;

--DESACTIVAR LOS TRIGGERS
ALTER TRIGGER TR_D_COMPUTADORA DISABLE;
ALTER TRIGGER TR_U_COMPUTADORA DISABLE;
ALTER TRIGGER TR_I_COMPUTADORA DISABLE;

--CREACION DE UN TRIGGER MULTIPLE DE INSERTAR, ACTUALIZAR, ELIMINAR
CREATE OR REPLACE TRIGGER TR_MULTIPLE_COMPUTADORA
AFTER INSERT OR DELETE OR DELETE ON COMPUTADORA
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(50);
    LV_FHECA DATE;
BEGIN
    --RECUPERAR UN ID, LA FECHA DEL SISTEMA Y EL USUARIO DEL SISTEMA
    --VAMOS A RECUPERAR UN ID VALIDO USANDO UNA SECUANCIA
    SELECT ID_BITACORA.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FHECA FROM DUAL;
    
    --CONDICION POR CUAL ACCION OCURRIRA DE TIPO DML
    IF INSERTING THEN 
    INSERT INTO BITACORA(ID_BITACORA, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD,
                        PRECIO_OLD, USUARIO, FECHA_NOW, MOVIMIENTIO)
    VALUES(LV_ID_BIT,:NEW.ID_COMPU,:NEW.MARCA, :NEW.MODELO, :NEW.RAM, :NEW.PROCESADOR, :NEW.PRECIO, NULL, NULL,0, NULL, 0,
            LV_USUARIO, LV_FHECA, 'INSERT' );
            
    --DE LO CONTRARIO A ACTUALIZAR
    ELSIF UPDATING THEN
    INSERT INTO BITACORA(ID_BITACORA, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD,
                        PRECIO_OLD, USUARIO, FECHA_NOW, MOVIMIENTIO)
    VALUES(LV_ID_BIT,:NEW.ID_COMPU, :NEW.MARCA, :NEW.MODELO, :NEW.RAM, :NEW.PROCESADOR, :NEW.PRECIO, :OLD.MARCA, :OLD.MODELO, :OLD.RAM, :OLD.PROCESADOR , :OLD.PRECIO,
            LV_USUARIO, LV_FHECA, 'UPDATE' );
    
    --DE LO CONTRARIO A ELIMINAR
    ELSIF DELETING THEN
    INSERT INTO BITACORA(ID_BITACORA, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD,
                        PRECIO_OLD, USUARIO, FECHA_NOW, MOVIMIENTIO)
    VALUES(LV_ID_BIT,:OLD.ID_COMPU, NULL, NULL,0, NULL, NULL, :OLD.MARCA, :OLD.MODELO, :OLD.RAM, :OLD.PROCESADOR , :OLD.PRECIO,
            LV_USUARIO, LV_FHECA, 'DELETE' );
    END IF;
            
END TR_MULTIPLE_COMPUTADORA;
/


SELECT * FROM COMPUTADORA;
SELECT * FROM BITACORA;

DROP TABLE BITACORA;

INSERT INTO COMPUTADORA VALUES (1, 'DEL', 'INSPIRON', 16, 'INTEL CORE i7 9th', 800);
            
--ACTUALIZAMOS
UPDATE COMPUTADORA SET 
    MARCA = 'HP'
WHERE ID_COMPU = 1;

--ELIMINAMOS
DELETE COMPUTADORA WHERE ID_COMPU = 1;


