---SENTENCIAS BASICAS Y FUNCIONES DE AGREGACION 

INSERT INTO EMPLEADO VALUES(1, 'FERNANDO','GOMEZ',25,'GERENTE GENERAL', 'PRODUCCION');
INSERT INTO EMPLEADO VALUES(2, 'GERARDO','LOPEZ',30,'AYUDANTE GENERAL', 'PRODUCCION');
INSERT INTO EMPLEADO VALUES(3, 'LILIANA','RUIZ',28,'AUX. ADMINISTRATIVO', 'RR.HH');
INSERT INTO EMPLEADO VALUES(4, 'HUMBERTO','DIAZ',27,'JEFE DE RECURSOS HUMANOS', 'RR.HH');
INSERT INTO EMPLEADO VALUES(5, 'MARIANA','VACA',32,'GERENTE DE VENTAS', 'VENTAS');

SELECT * FROM EMPLEADO;

--MODIFICAR CO MACBIAR EL NOMBRE DE UNA COLUMNA
ALTER TABLE EMPLEADO RENAME COLUMN APP TO APELLIDO; 

--ACTULIZAR UN REGSITRO 
UPDATE EMPLEADO SET NOMBRE = 'GABRIELA' WHERE  ID_EMPLEADO = 1;

--ORDER BY
SELECT * FROM EMPLEADO ORDER BY EDAD ASC;
SELECT * FROM EMPLEADO ORDER BY EDAD DESC;

--BUSQUEDA DE INFROMACION CON CARACTERES EN ESPECIFICO
--BUSCAR EMPLEADOS QUE SU NOMBRE EMPIEE CON LA LETRA "G"
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE 'G%';
--BUSCAR EMPLEADOS QUE SU NOMBRE CONTENGA LA LETRA I
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%I%';
--BUSCAR EMPLEADOS QUE SU NOMBRE TERMINE CON LA LETRA 'O'
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%O';

--USO DE LA TABLA DUAL: ES ES UNA TABLA VRITUAL QUE OFRECE ORACLE Y NOS PERMITE HACER CONSULTAS AUNQUE NO TENGAMOS
--VALORES DE UNA TABLA EXISTENTE, PUEDE SERVIR PARA OPEREACIONES 
SELECT 5 + 5 AS SUMA FROM DUAL;


--USO DE LA FUNCION LENGTH: CONTABILIZA LA LONGITUD DE UNA CADENA
SELECT LENGTH('ESTA ES UNA CADENA DE PRUEBA PARA EL USO DE LENGTH') AS TAMANIO FROM DUAL;

--BUSCAR CON MAS CONDICIONES 

--BUSCAR EMPLEADOS MAYORES DE 25
SELECT * FROM EMPLEADO WHERE EDAD > 25;

--Buscar empleados moner de 30
SELECT * FROM EMPLEADO WHERE EDAD < 30;

--BUSCAR EMPLEADOS DE MAYORES DE 24 Y MENORES DE 30
SELECT * FROM EMPLEADO WHERE EDAD > 25 and EDAD < 29;

-- USO DE RANFO BETTEN
SELECT * FROM EMPLEADO WHERE EDAD BETWEEN 25  AND 30;

-- BUSCAR EMPLEADOS CON EL ID 1, 3, 5
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO =1 OR ID_EMPLEADO =3 OR ID_EMPLEADO =5; 

-- LA FUNCION IN
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO IN(1,3,5)

--USO DE LA FUNCION GROUP BY 
SELECT DEPARTAMENTO FROM EMPLEADO GROUP BY DEPARTAMENTO;

-- CONTAR CUANTO EMPLEADOS POR DEPARTAMENTOS EXISTEN
SELECT DEPARTAMENTO, COUNT(ID_EMPLEADO) AS TOTAL_EMPLEADO FROM EMPLEADO GROUP BY DEPARTAMENTO;

-- CONTAR LOS EMPLEADOS QUE SEAN MAYORES DE 25
SELECT COUNT(ID_EMPLEADO) AS TOTAL_EMPLEADOS FROM EMPLEADO WHERE EDAD > 24;

-- FUNCION DE SUMA 
SELECT SUM(EDAD) AS SUMA_TOTAL FROM EMPLEADO;

-- BUSCAR LA EDAD MAXIMA DE LOS EMPLEADOS
SELECT MAX(EDAD) AS EDAD_MAXIMA FROM EMPLEADO;

-- BUSCAR LA EDAD MINIMA DE LOS EMPLEADOS
SELECT MIN(EDAD) AS EDAD_MINIMA FROM EMPLEADO;

-- BUSCAR EL PROMEDIO DE EDAD DE LOS EMPLEADOS
SELECT AVG(EDAD) AS PROMEDIO FROM EMPLEADO;

-- FUNCION DE REDONDEO
SELECT ROUND(AVG(EDAD), 0 ) AS EDAD_PROMEDIO FROM EMPLEADO;

-- USO DEL TO_CHAR PARA UN FORMATO DIFERENTE


-- DARLE UN FORMATO CON CONCAT
SELECT CONCAT(CONCAT(CONCAT(CONCAT('EL EMPLEADO',SELECT TO_CHAR(AVG(EDAD), 'fm99.00') AS PROMEDIO FROM EMPLEADO WHERE EDAD < 30; ' '), NOMBRE), ' '), APELLIDO) AS DETALLE FROM EMPLEADO;

-- DARLE UN FORMATO DIFERENTE CON PIPES O BARRA LATERAL ||
SELECT 'EL EMPLEADO(A) '||NOMBRE||' '||APELLIDO||' CON LA EDAD DE '||EDAD||' ANIOS, TRABAJA EN EL DEPARTAMENTO DE'||DEPARTAMENTO||' COMO '||PUESTO AS DETALLE FROM EMPLEADO;

--EJERCICIO
CREATE TABLE PELICULA(
    ID_PELICULA NUMBER,
    TITULO NVARCHAR2(50),
    DIRECTOR NVARCHAR2(50),
    GENERO NVARCHAR2(50),
    ANIO_ESTRENO NUMBER,
    DURACION_MINU NUMBER,
    RECAUDACION NUMBER,
    CONSTRAINT ID_PELICULA_PK PRIMARY KEY (ID_PELICULA)
);
DROP TABLE PELICULA;

-- AGREGAR
INSERT INTO PELICULA VALUES(1, 'TITANIC', 'JAMES CAMERON', 'ROMANCE', 1997, 195, 2000000);
INSERT INTO PELICULA VALUES(2, 'AVATAR', 'JAMES CAMERON', 'CIENCIA FICCION', 2009, 162, 50000000);
INSERT INTO PELICULA VALUES(3, 'EL SEÑOR DE LOS ANILLOS', 'PETTER J', 'FANTASIA', 1990, 200, 3000000);
INSERT INTO PELICULA VALUES(4, 'JOKER', 'TODD PHILLIPS', 'DRAMA', 2019, 122, 10000000);
INSERT INTO PELICULA VALUES(5, 'TOY STORY', 'JHON LESSERTER', 'ANIMACION', 2019, 122, 1080000);
INSERT INTO PELICULA VALUES(6, 'AVENGERS', 'ANTONY RUSO', 'ACCION', 2019, 181, 3783000);
INSERT INTO PELICULA VALUES(7, 'INTERSTELLAR' , 'CHRISTPHER', 'CIENCI FISION', 2014, 196, 1200000);

SELECT * FROM PELICULA;

