/*
FUNCIONES PL/SQL (FUNCTION ), ES UN BLOQUE QUE RECIBE PARAMAETROS DE ENTRADA(OPCIONAL), SE EJECUTA UNSA SERIE 
INSTRUCCIONES Y DEVUELVE UN VALOR CON LA CLAUSA RETURN

SE USAN MUCHO CUANDO SE REQUIERE REUTILIZAR CODIGO QUE SIEMPRE RETORNA (A DIFERENCIA DE UN PROCEDIMIENTO ALMACENADO
QUE NO NECESARIAMENTE RETORNA ALGO).

IMPORTANTE: EN LOS PARAMAETROA HAY QUE COLOCAR EL TIPO DE DATO
*/

--EJEMPLO
CREATE OR REPLACE FUNCTION SUMA(A NUMBER, B NUMBER) RETURN NUMBER
IS
    RESULTADO NUMBER;
BEGIN 
    RESULTADO := A +B;
    RETURN RESULTADO;
END;
/

--LLAMADA MEDIANTE UN BLOQUE ANONIMO
BEGIN 
    DBMS_OUTPUT.PUT_LINE('EL RESULTADO DE LA SUMA ES: ' || SUMA(2,2));
END;
/

--OTRA OPCION ES CON UNA CONSULTA COMUN
SELECT SUMA(2,2) FROM DUAL;


----------------------------------------------------------------------------------------------------------------------------
--CALCULAR EL AREA DEUN CIRCULO
CREATE OR REPLACE FUNCTION AREA_CIRCULO(RADIO NUMBER) RETURN NUMBER
IS
BEGIN
    RETURN 3.1416 * (RADIO * RADIO);
END;
/

--LLAMAMOS POR BLOQUE ANONIMO
BEGIN DBMS_OUTPUT.PUT_LINE('EL AREA DEL CIRCULO ES: ' || AREA_CIRCULO(3));
END;
/



