--SECUENCIA(SEQUENCE): BLOQUE QUE AYUDA A CREA VALORES SECUENCIALES ENTEROS
--GENERALMENTE SE USAN PARA CUMPLIR CON REGLAS DE CONSTRAINT CON EL USO DE LLAVES PRIMARIAS UNICAS

CREATE SEQUENCE ID_BITACORA
START WITH 1 
MINVALUE 1
MAXVALUE 9999
NOCACHE
NOCYCLE;

SELECT ID_BITACORA.NEXTVAL FROM DUAL;
