SELECT USER FROM DUAL;
SELECT SYSDATE FROM DUAL;

--CAMBIAR EL FORMATO
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

SELECT NVL(MAX(ID_BITACORA),0) + 1 FROM BITACORA; --NVL ES PARA VALIDAD VALORES NULOS

