--TRIGGER A NIVEL SENTENCIA(STATEMNT): ACTUA UNICAMENTE POR CADA TIPO DE OPERACION DML EXISTENTE 
--SI RECIBE UNA SOLA SOLICITUD DE ELIMINACION DE VARIOS REGISTROS, ACTUARA UNA SOLA VES

--EJEMPLO PARA COMPUTADORA
CREATE OR REPLACE TRIGGER TR_M_COMPUTADORA
AFTER INSERT OR UPDATE OR DELETE ON COMPUTADORA
--NO EXISTE EL FOR EACH ROW
DECLARE 
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(50);
    LV_FECHA DATE;
    LV_MOV NVARCHAR2(50);
BEGIN
    SELECT ID_BITACORA.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;

    IF INSERTING THEN 
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;
        INSERT INTO BITACORA(ID_BITACORA, USUARIO, FECHA_NOW, MOVIMIENTIO)
        VALUES (LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOV);
END TR_M_COMPUTADORA;
/


SELECT * FROM COMPUTADORA;   
SELECT * FROM BITACORA;

DELETE FROM COMPUTADORA;
DELETE FROM BITACORA; 
INSERT INTO COMPUTADORA VALUES(3, 'HP', 'PAVILION', 12, 'I5', 12000); --PRIMERA SENTENCIA    
INSERT INTO COMPUTADORA VALUES(4, 'DEL', 'INSPIRION', 18, 'I8', 1500); --SEGUNDA SENTENCIA    
    

--TRIGGER A NIVEL SENTENCIA(STATEMNT): ACTUA UNICAMENTE POR CADA TIPO DE OPERACION DML EXISTENTE 
--SI RECIBE UNA SOLA SOLICITUD DE ELIMINACION DE VARIOS REGISTROS, ACTUARA UNA SOLA VES

--EJEMPLO PARA ESTUDIANTES
CREATE OR REPLACE TRIGGER TR_M_ESTUDIANTE
AFTER INSERT OR UPDATE OR DELETE ON ESTUDIANTE
--NO EXISTE EL FOR EACH ROW
DECLARE 
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(50);
    LV_FECHA DATE;
    LV_MOV NVARCHAR2(50);
BEGIN
    SELECT ID_BITACORA_E.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;

    IF INSERTING THEN 
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;
        INSERT INTO BITACORA_E(ID_BITACORA_E, USUARIO, FECHA_NOW, MOVIMIENTIO)
        VALUES (LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOV);
END TR_M_ESTUDIANTE;
/


SELECT * FROM ESTUDIANTE;   
SELECT * FROM BITACORA_E;

DELETE FROM ESTUDIANTE;
DELETE FROM BITACORA_E; 

INSERT INTO ESTUDIANTE VALUES(1, 'JUAN', 'MARTINEZ', 22, 'ING.INDUSTRIAL', 5, 2024); --PRIMERA SENTENCIA    
INSERT INTO ESTUDIANTE VALUES(2, 'MAX', 'JUAREZ', 19, 'ING.INFORMATICA', 4, 2020); --SEGUNDA SENTENCIA    
    
    
    
    
    
    
    
    
    