--EXAMEN
--CREACION DE LAS TABLAS

--TABLA EQUIPOS
CREATE TABLE EQUIPOS(
    NOMBRE_EQUIPO NVARCHAR2(20),
    CIUDAD NVARCHAR2(30),
    CONFERENCIA NVARCHAR2(30),
    DIVISION NVARCHAR2(15),
    CONSTRAINT NOMBRE_PK PRIMARY KEY(NOMBRE_EQUIPO)
);

DROP TABLE EQUIPOS;
DROP TABLE PARTIDOS;
DROP TABLE JUGADORES;
DROP TABLE ESTADISTICAS;
--TABLA PARTIDO
CREATE TABLE PARTIDOS(
    CODIGO NUMBER,
    EQUIPO_LOCAL NVARCHAR2(30),
    EQUIPO_VISITANTE NVARCHAR2(30),
    PUNTOS_LOCAL NUMBER,
    PUNTOS_VISITANTE NUMBER,
    TEMPORADA NVARCHAR2(30),
    CONSTRAINT COIDGO_PK PRIMARY KEY(CODIGO),
    CONSTRAINT EQUI_LOCAL_FK FOREIGN KEY(EQUIPO_LOCAL) REFERENCES EQUIPOS(NOMBRE_EQUIPO),
    CONSTRAINT EQUI_VISIT_FK FOREIGN KEY(EQUIPO_VISITANTE) REFERENCES EQUIPOS(NOMBRE_EQUIPO)
);
DROP TABLE EQUIPOS;
--TABLA JUGADORES
CREATE TABLE JUGADORES(
    CODIGO NUMBER,
    NOMBRE NVARCHAR2(30),
    PROCEDENCIA NVARCHAR2(30),
    ALTURA NVARCHAR2(30),
    PESO NUMBER,
    POSICION NVARCHAR2(30),
    NOMBRE_EQUIPO NVARCHAR2(30),
    CONSTRAINT CODIGO_PK PRIMARY KEY(CODIGO),
    CONSTRAINT NOMBRE_EQUIPO_FK FOREIGN KEY (NOMBRE_EQUIPO) REFERENCES EQUIPOS() 
);
NOMBRE_EQUIPO
--TABLA ESTADISTICAS
CREATE TABLE ESTADISTICAS(
    TEMPORADA NVARCHAR2(30),
    JUGADOR NUMBER,
    PUNTOS_POR_PARTIDO FLOAT,
    ASISTENCIAS_POR_PARTIDO FLOAT,
    TAPONES_POR_PARTIDO FLOAT,
    REBOTES_POR_PARTIDO FLOAT,
    CONSTRAINT TEMP_PK PRIMARY KEY(TEMPORADA, JUGADOR),
    CONSTRAINT JUGADOR_FK FOREIGN KEY(JUGADOR) REFERENCES JUGADORES(CODIGO)
);

--1.Mostrar el nombre de todos los jugadores ordenados alfabéticamente. (Debe devolver 432 registros.)
SELECT NOMBRE, PROCEDENCIA, ALTURA, PESO, POSICION, NOMBRE_EQUIPO FROM JUGADORES
ORDER BY NOMBRE ASC;

--2.Mostrar el nombre de todos los equipos ordenados alfabéticamente.
SELECT NOMBRE_EQUIPO, CIUDAD, CONFERENCIA, DIVISION FROM EQUIPOS
ORDER BY NOMBRE_EQUIPO ASC;

--3.Mostrar el nombre de los equipos del este.
SELECT NOMBRE_EQUIPO, CIUDAD, DIVISION, CONFERENCIA FROM EQUIPOS
WHERE CONFERENCIA = 'East';

--4.Mostrar los equipos donde su ciudad empieza por c.
SELECT NOMBRE_EQUIPO, CIUDAD, CONFERENCIA, DIVISION FROM EQUIPOS
WHERE CIUDAD LIKE 'C%';

--5.Mostrar todos los jugadores y su equipo ordenado por nombre del equipo. (Debe devolver 432 registros)
SELECT E.NOMBRE_EQUIPO ,J.NOMBRE AS NOMBRE_JUGADORES
FROM JUGADORES J INNER JOIN EQUIPOS E 
ON J.NOMBRE_EQUIPO = E.NOMBRE_EQUIPO
ORDER BY E.NOMBRE_EQUIPO ASC;

--6.Mostrar todos los jugadores del equipo «Raptors».
SELECT E.NOMBRE_EQUIPO ,J.NOMBRE AS NOMBRE_JUGADORES
FROM JUGADORES J INNER JOIN EQUIPOS E 
ON J.NOMBRE_EQUIPO = E.NOMBRE_EQUIPO
WHERE E.NOMBRE_EQUIPO = 'Raptors'
ORDER BY J.NOMBRE ASC;

--7.Mostrar los puntos por partido de ‘Pau Gasol’.
SELECT J.NOMBRE, E.PUNTOS_POR_PARTIDO
FROM JUGADORES J INNER JOIN ESTADISTICAS E
ON  J.CODIGO = E.JUGADOR
WHERE J.NOMBRE = 'Pau Gasol';

--8.Mostrar los puntos por partido de ‘Pau Gasol’ en la temporada ’04/05′.
SELECT J.NOMBRE, E.PUNTOS_POR_PARTIDO, E.TEMPORADA
FROM JUGADORES J INNER JOIN ESTADISTICAS E
ON  J.CODIGO = E.JUGADOR
WHERE J.NOMBRE = 'Pau Gasol' AND E.TEMPORADA = '04/05';

--9.Mostrar el número de puntos de cada jugador en toda su carrera. (Debe devolver 424 registros.)
SELECT J.NOMBRE, COUNT(E.PUNTOS_POR_PARTIDO) AS TOTAL_PUNTO
FROM JUGADORES J INNER JOIN ESTADISTICAS E
ON  J.CODIGO = E.JUGADOR
GROUP BY J.NOMBRE
ORDER BY TOTAL_PUNTO DESC;

--10.Mostrar el número de jugadores de cada equipo.
SELECT E.NOMBRE_EQUIPO, COUNT(J.CODIGO) AS TOTAL_JUGADORES
FROM EQUIPOS E INNER JOIN JUGADORES J 
ON  J.NOMBRE_EQUIPO = E.NOMBRE_EQUIPO
GROUP BY E.NOMBRE_EQUIPO
ORDER BY TOTAL_JUGADORES DESC;

--11.Mostrar el jugador que más puntos ha realizado en toda su carrera.
SELECT J.NOMBRE, COUNT(E.PUNTOS_POR_PARTIDO) AS TOTAL_PUNTO
FROM JUGADORES J INNER JOIN ESTADISTICAS E
ON  J.CODIGO = E.JUGADOR
GROUP BY J.NOMBRE
ORDER BY TOTAL_PUNTO DESC
FETCH FIRST 1 ROW ONLY;

--12.Mostrar el nombre del equipo, conferencia y división del jugador más alto de la NBA.
SELECT J.ALTURA,J.NOMBRE, E.NOMBRE_EQUIPO, E.CONFERENCIA, E.DIVISION
    FROM EQUIPOS E INNER JOIN JUGADORES J 
    ON  J.NOMBRE_EQUIPO = E.NOMBRE_EQUIPO
ORDER BY J.ALTURA DESC
FETCH FIRST 1 ROW ONLY;

--13.Mostrar el partido o partidos (equipo_local, equipo_visitante y diferencia) con mayor diferencia de puntos. (CREAR UNA VIEW)
CREATE OR REPLACE VIEW V_DIFERENCIA_PUNTOS AS
SELECT EQUIPO_LOCAL, EQUIPO_VISITANTE, 
       ABS(PUNTOS_LOCAL - PUNTOS_VISITANTE) AS DIFERENCIA
FROM PARTIDOS 

--LO MANDAMOS A LLAMAR
SELECT * FROM V_DIFERENCIA_PUNTOS;

--14.Mostrar la media de puntos en partidos de los equipos de la división Pacific. 
CREATE OR REPLACE VIEW V_PUNTOS_DIVICION AS
SELECT AVG(puntos) AS MEDIA_PUNTOS_PACIFIC
FROM (
    SELECT SUM(PUNTOS_LOCAL) AS puntos
    FROM PARTIDOS 
    WHERE EQUIPO_LOCAL IN (
        SELECT NOMBRE_EQUIPO FROM EQUIPOS WHERE UPPER(DIVISION) = 'PACIFIC'
    )
    
    UNION ALL
    
    SELECT SUM(PUNTOS_VISITANTE) AS puntos
    FROM PARTIDOS 
    WHERE EQUIPO_VISITANTE IN (
        SELECT NOMBRE_EQUIPO FROM EQUIPOS WHERE UPPER(DIVISION) = 'PACIFIC'
    )
) TOTAL;

SELECT * FROM V_PUNTOS_DIVICION; 

--15.Mostrar los puntos de cada equipo en los partidos, tanto de local como de visitante. Usa una vista (CREAR UNA VIEW)
CREATE OR REPLACE VIEW V_PUNTOS_EQUIPO AS
SELECT 
    EQUIPO,
    SUM(PUNTOS_LOCAL) AS PUNTOS_COMO_LOCAL,
    SUM(PUNTOS_VISITANTE) AS PUNTOS_COMO_VISITANTE
FROM (
    -- Equipos LOCALES
    SELECT EQUIPO_LOCAL AS EQUIPO, PUNTOS_LOCAL, 0 AS PUNTOS_VISITANTE
    FROM PARTIDOS
    
    UNION ALL
    
    -- Equipos VISITANTES
    SELECT EQUIPO_VISITANTE, 0, PUNTOS_VISITANTE
    FROM PARTIDOS
) puntos
GROUP BY EQUIPO;

SELECT * FROM V_PUNTOS_EQUIPO

