--ACTIVIDAD DE PRACTICA

CREATE TABLE CINE(
    ID_CINE NUMBER,
    NOMBRE NVARCHAR2(50),
    CIUDAD NVARCHAR2(50),
    SALA NUMBER,
    TIPO NUMBER, --1.TRADICIONAL, 2.VIP, 3.IMAX
    CONSTRAINT CINE_PK PRIMARY KEY(ID_CINE)
);

INSERT INTO CINE VALUES (1, 'Cinepolis Plaza', 'Ciudad de México', 12, 1);
INSERT INTO CINE VALUES (2, 'Cinemex Perisur', 'Ciudad de México', 8, 2);
INSERT INTO CINE VALUES (3, 'Cinepolis VIP', 'Guadalajara', 6, 2);
INSERT INTO CINE VALUES (4, 'IMAX Santa Fe', 'Ciudad de México', 4, 3);
INSERT INTO CINE VALUES (5, 'Cine Tradicional', 'Monterrey', 5, 1);
INSERT INTO CINE VALUES (6, 'Cinepolis', 'Puebla', NULL, 1);  
INSERT INTO CINE VALUES (7, 'Cinemex', 'León', 7, NULL);   
INSERT INTO CINE VALUES (8, 'Mega Cine', 'Tijuana', 10, 1);
INSERT INTO CINE VALUES (9, 'Cine Royal', 'Cancún', NULL, NULL); 
INSERT INTO CINE VALUES (10, 'IMAX Premium', 'Guadalajara', 5, 3);

CREATE TABLE FUNCION(
    ID_FUNCION NUMBER,
    PELICULA NVARCHAR2(50),
    DURACION NUMBER,
    HORARIOS NVARCHAR2(50),
    ID_CINE NUMBER,
    CLASIFICACION NUMBER, --1.A 2.B 3.C 4.PG13 5.R
    CONSTRAINT FUNCION_PK PRIMARY KEY(ID_FUNCION),
    CONSTRAINT CINE_FK FOREIGN KEY(ID_CINE) REFERENCES CINE(ID_CINE)
);

INSERT INTO FUNCION VALUES (1, 'Avengers: Endgame', 181, '15:30', 1, 1);
INSERT INTO FUNCION VALUES (2, 'The Batman', 176, '18:45', 2, 4);
INSERT INTO FUNCION VALUES (3, 'Spider-Man: No Way Home', 148, '20:15', 3, 1);
INSERT INTO FUNCION VALUES (4, 'Dune', 155, '16:20', 4, 4);
INSERT INTO FUNCION VALUES (5, 'Joker', 122, '22:00', 5, 5);
INSERT INTO FUNCION VALUES (6, 'Toy Story 4', 100, '14:00', 1, 1);
INSERT INTO FUNCION VALUES (7, 'John Wick 4', 169, '19:30', 2, 5);
INSERT INTO FUNCION VALUES (8, 'Frozen 2', 103, '13:45', 3, 1);
INSERT INTO FUNCION VALUES (9, 'The Godfather', 175, '21:00', 4, 5);
INSERT INTO FUNCION VALUES (10, 'Finding Nemo', 100, '12:30', 5, 1);
INSERT INTO FUNCION VALUES (11, 'Deadpool', 108, '23:15', 1, 5);
INSERT INTO FUNCION VALUES (12, 'Inception', 148, '17:00', NULL, 4); 
INSERT INTO FUNCION VALUES (13, 'Interstellar', 169, '19:45', 2, NULL);  L
INSERT INTO FUNCION VALUES (14, 'La La Land', 128, '16:10', NULL, NULL);  
INSERT INTO FUNCION VALUES (15, 'Parasite', 132, '20:30', 4, 5);
INSERT INTO FUNCION VALUES (16, 'Black Panther', 134, '15:15', 5, 4);
INSERT INTO FUNCION VALUES (17, 'The Shawshank Redemption', 142, '18:20', 1, 5);
INSERT INTO FUNCION VALUES (18, 'Pulp Fiction', 154, '21:45', 2, 5);
INSERT INTO FUNCION VALUES (19, 'Forrest Gump', 142, '14:50', NULL, 2);  
INSERT INTO FUNCION VALUES (20, 'The Matrix', 136, '22:30', 4, 4);

--1 MOSTRAR TODAS LAS FUNCIONES CON EL NOMBRE DEL CINE Y USAR CASE PARA MOSTRAR EL TIPO DEL CINE Y LA CLASIFICACION DE LA FUNCION
SELECT * FROM FUNCION;
SELECT C.NOMBRE AS CINE, F.PELICULA AS PELICULA,
(CASE
WHEN TIPO = 1 THEN 'TRADICIONAL'
WHEN TIPO = 2 THEN 'VPI'
WHEN TIPO = 3 THEN 'IMAX'
ELSE 'SIN TIPO'
END) AS TIPO,
(CASE
WHEN CLASIFICACION = 1 THEN 'A'
WHEN CLASIFICACION = 2 THEN 'B'
WHEN CLASIFICACION = 3 THEN 'C'
WHEN CLASIFICACION = 4 THEN 'PG13'
WHEN CLASIFICACION = 5 THEN 'R'
ELSE 'SIN CLASIFICACION'
END) AS CLASIFICACION
FROM FUNCION F 
INNER JOIN CINE C ON F.ID_CINE = C.ID_CINE;

--2 CONTAR CUANTAS FUNCIONES HAY POR CINE
SELECT C.NOMBRE, COUNT(*) AS TOTAL_FUNCIONES
FROM FUNCION F
INNER JOIN CINE C ON F.ID_CINE =C.ID_CINE
GROUP BY C.NOMBRE;

--3 MOSTRAR LA FUNCON CON MAYOR DURACCION Y CONCATENER 'MINUTOS' AL RESULTADO
SELECT PELICULA, CONCAT(MAX(DURACION), ' MINUTOS') AS DURACION FROM FUNCION
GROUP BY PELICULA 
ORDER BY DURACION DESC;

--4 MOTRAR EL CINE CON MAS FUNCIONES PROGRAMADAS
SELECT C.NOMBRE, COUNT(*) AS TOTAL_FUNCIONES
FROM FUNCION F
INNER JOIN CINE C ON F.ID_CINE = C.ID_CINE
GROUP BY C.NOMBRE
ORDER BY TOTAL_FUNCIONES DESC
FETCH FIRST 1 ROW ONLY;

--5 MOSTRAR CUANTAS FUNCIONES PROGRAMADAS TIENE CADA CINE(NOMBRE DEL CINE Y EL NUMERO DE FUNCIONES)
SELECT C.NOMBRE, COUNT(*) AS NUMERO_FUNCIONES
FROM FUNCION F
LEFT JOIN CINE C ON F.ID_CINE = C.ID_CINE
GROUP BY C.NOMBRE;

--6 ORDENAR LAS PELICULAS POR NOMBRE
SELECT PELICULA, DURACION, HORARIOS, CLASIFICACION FROM FUNCION
ORDER BY PELICULA ASC;

--7 ORDENAR LOS CINES POR CIUDAD Y LUEGO POR NUMERO DE SALAS(EN UNA SOLSA CONSULTA)
SELECT NOMBRE, CIUDAD, SALA, TIPO FROM CINE
ORDER BY CIUDAD ASC, SALA DESC;

--8 MOSTRAR EL TOTAL DE DE LAS PELICULAS PROYECTADAS  EN CADA CINE
SELECT C.NOMBRE AS NOMBRE_CINE, COUNT(*) AS NUMERO_FUNCIONES
FROM FUNCION F
INNER JOIN CINE C ON F.ID_CINE = C.ID_CINE
GROUP BY C.NOMBRE
ORDER BY C.NOMBRE;

--9 MOSTRAR LA FUNCIONES CON LA PELICULA MAS LARGA DE CADA CINE
SELECT F.ID_FUNCION, F.PELICULA, F.DURACION, F.HORARIOS, F.CLASIFICACION, C.NOMBRE AS NOMBRE_CINE
FROM FUNCION F
INNER JOIN CINE C ON F.ID_CINE = C.ID_CINE
WHERE F.DURACION = (
    SELECT MAX(DURACION)
    FROM FUNCION
    WHERE ID_CINE = F.ID_CINE
)
ORDER BY F.DURACION DESC, C.NOMBRE;

--10 MOSTRAR LA FUNCIONES QUE NO TIENEN UN CINE ASIGNADO
SELECT F.PELICULA, C.NOMBRE AS NOMBRE_CINE
FROM FUNCION F
FULL JOIN CINE C ON F.ID_CINE = C.ID_CINE
WHERE C.NOMBRE IS NULL;

--11 MOSTRAR LOS CINES QUE NO TIENEN FUNCIONES ASIGNADAS
SELECT C.NOMBRE, F.PELICULA AS NOMBRE_PELICULA
FROM CINE C
FULL JOIN FUNCION F ON C.ID_CINE = F.ID_CINE
WHERE F.PELICULA IS NULL;

--12 CREAR UNA FUNCIONES USANDO CONCANT O || PARA DESGLOSAR EL DETALLE DE AMBAS TABLAS Y USANDO LOS RESPECTIVOS CASE
--EJEMPLO: LA FUNCION DE MATRIX SE PROYECTA EN EL CINE TRADICIONAL CINEMEX DE LEON A LAS 22:30, DURA 134 MINUTOS Y DE CLASIFICACION R
SELECT 'LA FUNCION DE ' ||F.PELICULA||' SE PROYECTA EN EL CINE ' 
||
(CASE
WHEN C.TIPO = 1 THEN ' TRADICIONAL '
WHEN C.TIPO = 2 THEN ' VPI '
WHEN C.TIPO = 3 THEN ' IMAX '
ELSE 'SIN TIPO'
END)
||C.NOMBRE||' DE '||C.CIUDAD||' A LAS '||F.HORARIOS||' ,DURA '||F.DURACION||' MINUTOS Y DE LA CLASIFICACION: '||
(CASE
WHEN F.CLASIFICACION = 1 THEN ' A '
WHEN F.CLASIFICACION = 2 THEN ' B '
WHEN F.CLASIFICACION = 3 THEN ' C '
WHEN F.CLASIFICACION = 4 THEN ' PG13 '
WHEN F.CLASIFICACION = 5 THEN ' R '
ELSE 'SIN CLASIFICACION'
END) 
FROM FUNCION F
INNER JOIN CINE C ON F.ID_CINE = C.ID_CINE


















