/*EJERCICIO DE VISTAS COMPLEJAS SOBRE LA TABLAS DE CINE Y FUNCUION

1..MOSTRAR LAS FUNCIONES DE CADA CINE
2..MOSTRAR EL TOTAL DE FUNCIONES QUE TIENE CADA CINE
3..MOSTRAR EL DETALLE DE LA INFORMACION USANDO CONCANT O || Y USANDO LOS RESPECTIVOS CASE DE CADA ENTIDAD
4..MUESTRA SOLO LOS CINES DE GUADALAGARA Y SUS FUNCIONES PROGRAMADAS
5..MUESTRA SOLO LAS PELICULAS DE CLASIFICACION R Y EL CINE EN DONDE SE PROYECTARA
*/

--1..MOSTRAR LAS FUNCIONES DE CADA CINE 
CREATE OR REPLACE VIEW V_FUNCIO_CINE AS
SELECT C.NOMBRE,F.PELICULA, F.DURACION
FROM FUNCION F
INNER JOIN CINE C
ON F.ID_CINE = C.ID_CINE
ORDER BY C.NOMBRE;

--LLAMAMOS A LA VISTA
SELECT * FROM V_FUNCIO_CINE;

--2..MOSTRAR EL TOTAL DE FUNCIONES QUE TIENE CADA CINE
CREATE OR REPLACE VIEW V_FUNCIO_CINE_CANT AS
SELECT C.NOMBRE,COUNT(F.PELICULA) AS TOTAL_PELIS
FROM FUNCION F
INNER JOIN CINE C
ON F.ID_CINE = C.ID_CINE
GROUP BY C.NOMBRE;

--LAMMAMOS A LA VISTA
SELECT * FROM V_FUNCIO_CINE_CANT;


--3..MOSTRAR EL DETALLE DE LA INFORMACION USANDO CONCANT O || Y USANDO LOS RESPECTIVOS CASE DE CADA ENTIDAD
CREATE OR REPLACE VIEW V_DETALLE AS
SELECT 'LA FUNCION DE ' ||F.PELICULA||' SE PROYECTA EN EL CINE ' 
||
(CASE
WHEN C.TIPO = 1 THEN ' TRADICIONAL '
WHEN C.TIPO = 2 THEN ' VPI '
WHEN C.TIPO = 3 THEN ' IMAX '
ELSE 'SIN TIPO'
END)
||C.NOMBRE||' DE '||C.CIUDAD||' A LAS '||F.HORARIOS||' ,DURA '||F.DURACION||' MINUTOS Y DE LA CLASIFICACION: '||
(CASE
WHEN F.CLASIFICACION = 1 THEN ' A '
WHEN F.CLASIFICACION = 2 THEN ' B '
WHEN F.CLASIFICACION = 3 THEN ' C '
WHEN F.CLASIFICACION = 4 THEN ' PG13 '
WHEN F.CLASIFICACION = 5 THEN ' R '
ELSE 'SIN CLASIFICACION'
END) AS DETALLE
FROM FUNCION F
INNER JOIN CINE C ON F.ID_CINE = C.ID_CINE

--LLAMAMOS A LA FUNCION
SELECT * FROM V_DETALLE

--4..MUESTRA SOLO LOS CINES DE GUADALAGARA Y SUS FUNCIONES PROGRAMADAS
CREATE OR REPLACE VIEW V_CINE_GUADA_FUNCI AS
SELECT C.NOMBRE, C.CIUDAD, F.PELICULA
FROM FUNCION F
INNER JOIN CINE C
ON F.ID_CINE = C.ID_CINE
WHERE CIUDAD = 'Guadalajara';

--LLAMAMOS A NUESTRA VISTA
SELECT * FROM V_CINE_GUADA_FUNCI;

--5..MUESTRA SOLO LAS PELICULAS DE CLASIFICACION R Y EL CINE EN DONDE SE PROYECTARA
CREATE OR REPLACE VIEW V_FUNCION_CL AS
SELECT F.PELICULA,
    (CASE
    WHEN F.CLASIFICACION = 1 THEN ' A '
    WHEN F.CLASIFICACION = 2 THEN ' B '
    WHEN F.CLASIFICACION = 3 THEN ' C '
    WHEN F.CLASIFICACION = 4 THEN ' PG13 '
    WHEN F.CLASIFICACION = 5 THEN ' R '
    ELSE 'SIN CLASIFICACION'
    END) AS CLASIFICACION,
C.CIUDAD, C.NOMBRE 
FROM FUNCION F INNER JOIN CINE C
ON F.ID_CINE = C.ID_CINE
WHERE CLASIFICACION = 5;

--LALAMOS A NUESTRA VISTA
SELECT * FROM V_FUNCION_CL;


SELECT * FROM FUNCION;
SELECT * FROM CINE;














