--EJERCICIO
CREATE TABLE PELICULA(
    ID_PELICULA NUMBER,
    TITULO NVARCHAR2(50),
    DIRECTOR NVARCHAR2(50),
    GENERO NVARCHAR2(50),
    ANIO_ESTRENO NUMBER,
    DURACION_MINU NUMBER,
    RECAUDACION NUMBER,
    CONSTRAINT ID_PELICULA_PK PRIMARY KEY (ID_PELICULA)
);
DROP TABLE PELICULA;

-- AGREGAR
INSERT INTO PELICULA VALUES(1, 'TITANIC', 'JAMES CAMERON', 'ROMANCE', 1997, 195, 200000000);
INSERT INTO PELICULA VALUES(2, 'AVATAR', 'JAMES CAMERON', 'CIENCIA FICCION', 2009, 162, 900000000);
INSERT INTO PELICULA VALUES(3, 'EL SEÑOR DE LOS ANILLOS', 'PETTER J', 'FANTASIA', 1990, 200, 300000000);
INSERT INTO PELICULA VALUES(4, 'JOKER', 'TODD PHILLIPS', 'DRAMA', 2019, 122, 800000000);
INSERT INTO PELICULA VALUES(5, 'TOY STORY', 'JHON LESSERTER', 'ANIMACION', 2019, 122, 108000000);
INSERT INTO PELICULA VALUES(6, 'AVENGERS', 'ANTONY RUSO', 'CIENCIA FICCION', 2019, 181, 378300000);
INSERT INTO PELICULA VALUES(7, 'INTERSTELLAR' , 'CHRISTPHER', 'CIENCIA FICCION', 2014, 196, 120000000);

--ACTULIZAR UN REGSITRO 
UPDATE PELICULA SET GENERO = 'CIENCIA FICCION' WHERE  ID_PELICULA = 6;

SELECT * FROM PELICULA;

-- MOSTRAR LAS PELICULAS ORDENADAS POR RECAUDACION DE MAYOR A MENOR Y APLICAR FORMATO A LA MODENA ($1,750,000.00)
SELECT ID_PELICULA, TITULO, DIRECTOR, GENERO, ANIO_ESTRENO, DURACION_MINU, 
  TO_CHAR(RECAUDACION, 'L99G999G999G999D00', 'NLS_CURRENCY = ''$'' NLS_NUMERIC_CHARACTERS = ''.,''') AS RECAUDACION_FORMATO
  FROM PELICULA
ORDER BY RECAUDACION DESC;

-- CALCULAR EL PROMEDIO DE RECAUDACION DE LAS PELICULAS ESTRENADAS DEL AÑO 2000
SELECT AVG(RECAUDACION) FROM PELICULA WHERE ANIO_ESTRENO > 2000; 

-- MOSTRAR LAS PELICULAS QUE DUREN MAS DE 150 MINUTOS Y CONVERTIR EL TITULO  A MAYUSCULAS
SELECT LOWER(TITULO), DURACION_MINU FROM PELICULA WHERE DURACION_MINU > 150 
ORDER BY DURACION_MINU DESC;

-- CONSULTAR LOS REGUSTROS CUYO GENERO SEAN CICNCIA FICCION Y ORDENAR POR AÑO DE ESTRENO DEL MAS ANTIGUIA AL MAS RECIENTE
SELECT TITULO, GENERO, ANIO_ESTRENO FROM PELICULA WHERE GENERO = 'CIENCIA FICCION'
ORDER BY ANIO_ESTRENO ASC;

-- MOSTRAR LAS PELICULAS CUYA RECAUDACION ESTE ENTRE LOS 500,000,000 Y 1,500,000,000 Y AGREGAR EL FORMATO DE NONEDA
SELECT ID_PELICULA, TITULO, DIRECTOR, GENERO, ANIO_ESTRENO, DURACION_MINU, 
    TO_CHAR(RECAUDACION, 'L99G999G999G999D00', 'NLS_CURRENCY = ''$'' NLS_NUMERIC_CHARACTERS = ''.,''') AS RECAUDACION
    FROM PELICULA
    WHERE RECAUDACION BETWEEN 500000000 AND 1500000000;
    
-- MOSTRAR LAS PELICULAS DE GENERO ANIMACION Y AGREGAR AL FINAL DE LA RECAUDACION LA PALABRA 'DOLARES'
SELECT  TITULO ||' ES DE GENERO '|| ' ' ||GENERO||' Y UNA RECAUDACION DE ='||TO_CHAR(RECAUDACION, 'L99G999G999G999D00', 'NLS_CURRENCY = ''$'' NLS_NUMERIC_CHARACTERS = ''.,''')||' DOLARES '  AS DETALLE 
FROM PELICULA
WHERE GENERO = 'ANIMACION';

-- CONTAR CUANTAS PELICULAS HAY POR DIRECTOR 
SELECT DIRECTOR, COUNT(*) AS NUM_PELICULAS
FROM PELICULA
GROUP BY DIRECTOR;

-- MOSTRAR LA PELICULA CON MAYOR RECAUDACION AGREGAR EL FORMATO DE MODENA 
SELECT ID_PELICULA, TITULO, DIRECTOR, GENERO, ANIO_ESTRENO, DURACION_MINU, 
    TO_CHAR(RECAUDACION, 'L99G999G999G999D00', 'NLS_CURRENCY = ''$'' NLS_NUMERIC_CHARACTERS = ''.,''') AS RECAUDACION
    FROM PELICULA
    ORDER BY RECAUDACION DESC;
    
-- MOSTRAR LA PELICULA MAS ANIGUA Y ANTEPONER EL TEXTO 'ESTRENADA EN: '
SELECT 'ESTA PELICULA, ' || TITULO || ' ES LA MAS ANTIGUA QUE SE ESTRENO EN: ' || ANIO_ESTRENO AS MENSAJE
FROM PELICULA
WHERE ANIO_ESTRENO = (SELECT MIN(ANIO_ESTRENO) FROM PELICULA);

-- DESGLOSAR EL DETALLE DE LAS PELICULAS  EN UNSA SOLA LINEA CON CONCAT O ||  
SELECT 'lA PELICULA '||TITULO||' QUE FUE DIRIGIDA POR '||DIRECTOR||' CDEL GENERO '||GENERO||' QUE SE ESTRENO EN '||ANIO_ESTRENO||' CON UNA DURACION '||DURACION_MINU||' Y RECAUDO UN TOTAL DE: ' ||  
    TO_CHAR(RECAUDACION, 'L99G999G999G999D00', 'NLS_CURRENCY = ''$'' NLS_NUMERIC_CHARACTERS = ''.,''')||' DOLARES' AS DETALLES
    FROM PELICULA
--EJEMPLO : LA PELICULA DE TITANIC DIRIGIDA POR AUTOR, SE ESTRENO EN EL AÑO 1977, ES DE GENERO ROMANCE, TIENE UNA DURACION DE 198 MINUTOS Y RECAUDO UN TOTAL DE $ DOLARES 