--EJERCICIO DE PRACTICA DE CASE

CREATE TABLE PRODUCTO(
    ID_PRODUCTO NUMBER,
    NOMBRE NVARCHAR2(50),
    CATEGORIA NUMBER, --1:ALIMENTO, 2:BEBIDA, 3:ELECTRODOMOSTICO, 4:ROPA, 5:LIMPIEZA
    PRECIO NUMBER,
    STOCK NUMBER,
    MARCA NVARCHAR2(50),
    CONSTRAINT PRODUCTO_PK PRIMARY KEY(ID_PRODUCTO)
);

INSERT INTO PRODUCTO VALUES (1, 'Arroz integral', 1, 25.50, 100, 'La Costeña');
INSERT INTO PRODUCTO VALUES (2, 'Refresco de cola', 2, 18.00, 0, NULL);
INSERT INTO PRODUCTO VALUES (3, 'Licuadora', 3, 450.00, 15, 'Oster');
INSERT INTO PRODUCTO VALUES (4, 'Camisa manga larga', 4, 0, 50, 'Zara');
INSERT INTO PRODUCTO VALUES (5, 'Detergente líquido', 5, 35.75, 80, 'Ariel');
INSERT INTO PRODUCTO VALUES (6, 'Aceite de oliva', 1, 0, 25, 'Carbonell');
INSERT INTO PRODUCTO VALUES (7, 'Cerveza artesanal', 2, 45.00, 60, NULL);
INSERT INTO PRODUCTO VALUES (8, 'Microondas', 3, 800.00, 8, 'Samsung');
INSERT INTO PRODUCTO VALUES (9, 'Pantalón de mezclilla', 4, 299.90, 0, 'Levis');
INSERT INTO PRODUCTO VALUES (10, 'Jabón de tocador', 5, 12.50, 120, 'Dove');
INSERT INTO PRODUCTO VALUES (11, 'Atún enlatado', 1, 22.00, 75, 'Herdez');
INSERT INTO PRODUCTO VALUES (12, 'Agua mineral', 2, 10.00, 200, 'Bonafont');
INSERT INTO PRODUCTO VALUES (13, 'Ventilador', 3, 0, 12, 'Mabe');
INSERT INTO PRODUCTO VALUES (14, 'Calcetines deportivos', 4, 45.00, 90, 'Nike');
INSERT INTO PRODUCTO VALUES (15, 'Cloro líquido', 5, 15.00, 0, 'Cloralex');
INSERT INTO PRODUCTO VALUES (16, 'Frijoles refritos', 0, 18.50, 60, NULL);
INSERT INTO PRODUCTO VALUES (17, 'Jugo de naranja', 2, 28.00, 45, 'Jumex');
INSERT INTO PRODUCTO VALUES (18, 'Tostador', 3, 250.00, 20, 'Black and Decker');
INSERT INTO PRODUCTO VALUES (19, 'Chamarra', 4, 0, 25, 'Forever 21');
INSERT INTO PRODUCTO VALUES (20, 'Desinfectante', 5, 42.00, 65, 'Lysol');
INSERT INTO PRODUCTO VALUES (21, 'Sardinas en lata', 1, 16.00, 0, 'La Sirena');
INSERT INTO PRODUCTO VALUES (22, 'Café molido', 1, 85.00, 40, 'Nescafé');
INSERT INTO PRODUCTO VALUES (23, 'Vino tinto', 0, 0, 30, 'Concha y Toro');
INSERT INTO PRODUCTO VALUES (24, 'Aspiradora', 3, 1200.00, 5, 'Dyson');
INSERT INTO PRODUCTO VALUES (25, 'Falda', 4, 189.00, 35, NULL);

SELECT * FROM PRODUCTO;
--EJERCICIO 

--1.MUESTRA LOS PRODUCTOS CON SU CASE DE CATEGORIA
SELECT ID_PRODUCTO, NOMBRE, 
(CASE
WHEN CATEGORIA = 1 THEN 'ALIMENTO'
WHEN CATEGORIA = 2 THEN 'BEBIDA'
WHEN CATEGORIA = 3 THEN 'ELECTRODOMOSTICO'
WHEN CATEGORIA = 4 THEN 'ROPA'
WHEN CATEGORIA = 5 THEN 'LIMPIEZA'
ELSE 'VALOR DESCONOCIDO'
END) AS CATEGORIAS, PRECIO, STOCK, MARCA FROM PRODUCTO;

--2.CLASIFICA LOS PRODUCTOS POR SU PRECIO (CARO, MEDIO, BARATO)
SELECT ID_PRODUCTO, NOMBRE, CATEGORIA,
(CASE
WHEN PRECIO = 0 THEN ' SIN PRECIO'
WHEN PRECIO > 1000 THEN ' ES CARO: ' ||TO_CHAR(PRECIO, '9,999.0') || ' PESOS '
WHEN PRECIO >= 400 and PRECIO <=1000 THEN ' ES MEDIO: ' ||TO_CHAR(PRECIO, '9,999.0') || ' PESOS '
WHEN PRECIO <400 THEN ' ES BARATO: ' ||TO_CHAR(PRECIO, '9,999.0') || ' PESOS '
ELSE ' VALOR DESCONOCIDO'
END) AS PRECIO, STOCK, MARCA FROM PRODUCTO;

--3.CLASIFICA LOS PRODUCTOS POR STOCK (SOBRANTE, SUFICIENTE, ESCASO)
SELECT ID_PRODUCTO, NOMBRE, CATEGORIA, PRECIO,
(CASE
WHEN STOCK = 0 THEN ' ESCASO'
WHEN STOCK >0 AND STOCK <50 THEN ' SUFICIENTE'
WHEN STOCK >= 50 THEN ' SOBRANTE '
ELSE ' VALOR DESCONOCIDO'
END) AS STOCK, MARCA FROM PRODUCTO;

