--EJERCICIO DE FUNCIONES
--..1 CALCULAR EL AREA DE UN TRIANGULO
CREATE OR REPLACE FUNCTION AREA_TRIANGULO(B NUMBER, A NUMBER) RETURN NUMBER
IS
    --VARIABLE
    RESULTADO NUMBER;
BEGIN 
    RESULTADO := (B * A) / 2;
    RETURN RESULTADO;
END;
/

--LO LLAMAMOS POR UN BLOQUE ANONIMO
BEGIN
    DBMS_OUTPUT.PUT_LINE('EL AREA ES:' || AREA_TRIANGULO(5,8));
END;
/


--..2 CREAR UN FUNCION QUE RECIBA UN PARAMETRO E IMPRIMA SI EL NUMERO ES PAR O IMPAR
CREATE OR REPLACE FUNCTION PAR_IMPAR(N NUMBER) RETURN NVARCHAR2
IS
BEGIN 
    IF MOD(N,2) = 0 THEN
        RETURN 'PAR'; 
    ELSE 
        RETURN 'IMPAR';
    END IF;
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('EL NUMERO ES:' || PAR_IMPAR(8));
END;
/

--..3 UNA FUNCIONES QUE RECIBA UN TEXTO Y LO CONVIERTA A MAYUSCULA
CREATE OR REPLACE FUNCTION CONVERTIDOR(TEX NVARCHAR2) RETURN NVARCHAR2
IS
BEGIN 
    RETURN UPPER(TEX);
END;
/

// BLOQUE ANONIMO
BEGIN
    DBMS_OUTPUT.PUT_LINE('TEXTO EN MAYUSCULAS ' || CONVERTIDOR('hola mundo'));
END;
/

--..4 UNA FUNCION QUE RECIBA EL AÑO DE NACIMIENTO Y CALCULE LA EDAD APARTIR DE LA FEHCA DE NACIMIENTO
CREATE OR REPLACE FUNCTION CALCULAR_EDAD(FECHA DATE) RETURN NUMBER
IS
BEGIN       --EL FLOOR Redondea hacia abajo un número decimal al entero inmediatamente inferior o igual
    RETURN FLOOR(MONTHS_BETWEEN(SYSDATE, FECHA)/12); 
END;
/

--LO LLAMAMOS CON BLOQUE ANONIMO
BEGIN
    DBMS_OUTPUT.PUT_LINE('TINES ' ||CALCULAR_EDAD(TO_DATE('2001-03-31', 'YYYY-MM-DD')) || ' AÑOS');
END;
/
    
--..5 UNA FUNCION QUE RECIBA NOMBRE Y APELLIDO Y DEVULEVA SOLO LAS INICIALES
CREATE OR REPLACE FUNCTION INICIALES(NOMBRE NVARCHAR2, APELLIDO NVARCHAR2) RETURN NVARCHAR2
IS
    I_NOMBRE NVARCHAR2(1);
    I_APELLIDO VARCHAR2(2);
BEGIN
    I_NOMBRE := SUBSTR(NOMBRE, 1, 1);
    I_APELLIDO := SUBSTR(APELLIDO, 1, 1 );
    RETURN I_NOMBRE||' Y '|| I_APELLIDO;
END;
/

--LLAMAMOS CON BLOQUE ANONIMO
BEGIN
    DBMS_OUTPUT.PUT_LINE('LAS INICIALES SON '||INICIALES('MAX', 'MARTINEZ'));
END;
/

