--EJERCICIO 
/*
1..CREAR UNA TABLA TRABAJADOR(ID,NOMBRE, APELLIDO, CONTACTO, AREA, SALARIO)
2..CREAR UN PROCEDIMIENTO PARA RESPALDAR LA INFO
3..CREAR UN PROCEDIMIENTO PARA AUMENTARLES SU SALARIO UN 15%
*/

--1..CREAR UNA TABLA TRABAJADOR(ID,NOMBRE, APELLIDO, CONTACTO, AREA, SALARIO)
CREATE TABLE TRABAJADOR(
    ID_TRABAJADOR NUMBER,
    NOMBRE NVARCHAR2(50),
    APELLIDO NVARCHAR2(50),
    EDAD NUMBER,
    CONTACTO NUMBER,
    AREA NVARCHAR2(50),
    SALARIO NUMBER,
    CONSTRAINT TRABAJADOR_PK PRIMARY KEY(ID_TRABAJADOR)
);

DROP TABLE TRABAJADOR;

--1.1..TABLA DE RESPLADO
CREATE TABLE TRABAJAOR_PRD(
    ID_TRABAJADOR NUMBER,
    NOMBRE NVARCHAR2(50),
    APELLIDO NVARCHAR2(50),
    CONTACTO NUMBER,
    AREA NVARCHAR2(50),
    SALARIO NUMBER,
    CONSTRAINT TRABAJADOR_PRD_PK PRIMARY KEY(ID_TRABAJADOR)
);


INSERT INTO TRABAJADOR VALUES(1, 'Juan', 'Pérez',22, 5512345678, 'Sistemas', 15000);
INSERT INTO TRABAJADOR VALUES(2, 'María', 'López',26, 5598765432, 'Ventas', 12000);
INSERT INTO TRABAJADOR VALUES(3, 'Luis', 'García',55, 5545678912, 'Recursos Humanos', 13000);
INSERT INTO TRABAJADOR VALUES(4, 'Ana', 'Martínez',36, 5581234567, 'Sistemas', 15500);
INSERT INTO TRABAJADOR VALUES(5, 'Carlos', 'Ramírez',14, 5573456789, 'Ventas', 11000);
INSERT INTO TRABAJADOR VALUES(6, 'Sofía', 'Hernández',19, 5534567890, 'Contabilidad', 14000);
INSERT INTO TRABAJADOR VALUES(7, 'Jorge', 'González',50, 5598761234, 'Recursos Humanos', 12500);
INSERT INTO TRABAJADOR VALUES(8, 'Lucía', 'Fernández',45, 5519876543, 'Sistemas', 16000);
INSERT INTO TRABAJADOR VALUES(9, 'Miguel', 'Santos',31, 5567890123, 'Ventas', 11500);
INSERT INTO TRABAJADOR VALUES(10, 'Elena', 'Vargas',23, 5556789012, 'Contabilidad', 13500);
INSERT INTO TRABAJADOR VALUES(11, 'Pedro', 'Muñoz',24, 5587654321, 'Sistemas', 15800);
INSERT INTO TRABAJADOR VALUES(12, 'Marta', 'Rojas',19, 5523456789, 'Ventas', 11800);
INSERT INTO TRABAJADOR VALUES(13, 'Raúl', 'Castro',45, 5591234567, 'Recursos Humanos', 13000);
INSERT INTO TRABAJADOR VALUES(14, 'Isabel', 'Ortega',45, 5532198765, 'Contabilidad', 13800);
INSERT INTO TRABAJADOR VALUES(15, 'Alberto', 'Mendoza',25, 5543219876, 'Sistemas', 16200);
INSERT INTO TRABAJADOR VALUES(16, 'Patricia', 'Suárez',36, 5578901234, 'Ventas', 12200);
INSERT INTO TRABAJADOR VALUES(17, 'Fernando', 'Luna',38, 5513456789, 'Recursos Humanos', 12800);
INSERT INTO TRABAJADOR VALUES(18, 'Claudia', 'Salinas',40, 5598765431, 'Contabilidad', 14000);
INSERT INTO TRABAJADOR VALUES(19, 'Diego', 'Alvarez',45, 5561234567, 'Sistemas', 16500);
INSERT INTO TRABAJADOR VALUES(20, 'Gabriela', 'Torres',19, 5539876543, 'Ventas', 11900);

-----------------------------------------------------------------------------------------------
SELECT * FROM TRABAJAOR_PRD;
SELECT * FROM TRABAJADOR;

DELETE FROM TRABAJADOR;
DELETE FROM TRABAJAOR_PRD;

--PROCEDIMIENTO ALMACENADO
CREATE OR REPLACE PROCEDURE PR_RESPALDO_TRABAJADOR
IS
--DECLARACION DE VALORES, CONSTANTES O CURSOS
BEGIN
    --INSTRUCCIONES A EJECUTAR
    --LIMPIAR LA TABLA DE COMPUTADORA_PRD CON UNA SENTENCIA DELETE
    DELETE FROM TRABAJAOR_PRD;
    
    --REALIZAR EL RESPALDO DE COMPUTADORA EN COMPUTADORA_PRD CON INSERT INTO SELECT
    INSERT INTO TRABAJAOR_PRD(ID_TRABAJADOR, NOMBRE, APELLIDO ,CONTACTO, AREA ,SALARIO)
    SELECT ID_TRABAJADOR, NOMBRE, APELLIDO ,CONTACTO, AREA ,SALARIO FROM TRABAJADOR;

END PR_RESPALDO_TRABAJADOR;
/

--EJECUTAMOS EL PROCEDIMIENTO, ES DECIR HACE UN RESPALDO
EXECUTE PR_RESPALDO_TRABAJADOR;

------------------------------------------------------------------------------------------------------
--3..CREAR UN PROCEDIMIENTO PARA AUMENTARLES SU SALARIO UN 15%
CREATE OR REPLACE PROCEDURE APLICAR_AUMENTO(P_AUMENTO IN NUMBER) -->ESPERA UN DESCUENTASO
IS
BEGIN 
    UPDATE TRABAJADOR
    SET SALARIO = SALARIO + (SALARIO * (P_AUMENTO /100));
    --> PODEMOS COLOCAR EL COMMIT AQUI PERO YA NO PODRIAMOS HACER UN ROLLBACK
EXCEPTION
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('ERROR DE AUMENTO: '||SQLERRM);
END APLICAR_AUMENTO;
/

SELECT * FROM TRABAJADOR;

--EJECUTAMOS EL DESCUENTASO DEL PRODECIMIENTO
EXECUTE APLICAR_AUMENTO(15) --> AQUI PASAMOS EL PARAMETRO PARA EL DESCUENTASO

--SI NOS EQUIVOCAMOS A APLICAR EL DESCUENTO Y SI NO HICIMOS COMIT ENTONTES PODEMOS HACER UN ROLLBACK PARA REGRESAR LOS VALORES
ROLLBACK;

COMMIT; --CONFIRMAMOS PERO YA NO PODRIAMOS HACER UN ROLLBACK, ALMENOS QUE AGAMOS OTROS PROCEDURE QUE LE AUMENTE LO QUE SE LE DESCONTO








