
--CREAR UNA TABLA PARA LA ENTIDAD DE ESTUDIANTE (NOMBRE, APELLIDO, EDAD, CARRERA, SEMESTRE AÑO_INGRESO)
CREATE TABLE ESTUDIANTE(
    ID_ESTUDIANTE NUMBER,
    NOMBRE NVARCHAR2(50),
    APELLIDO NVARCHAR2(50),
    EDAD NUMBER,
    CARRERA NVARCHAR2(50),
    SEMESTRE NUMBER,
    AÑO_INGRESO NUMBER,
    CONSTRAINT ESTUDIANTE_PK PRIMARY KEY(ID_ESTUDIANTE)
);
SELECT * FROM ESTUDIANTE;

--CREAR CREAR SU RESPECTIVA BITACORA
CREATE TABLE BITACORA_E(
    ID_BITACORA_E NUMBER,
    
    --VALORES NUEVOS :NEW
    ID_ESTUDIANTE NUMBER,
    NOMBRE NVARCHAR2(50),
    APELLIDO NVARCHAR2(50),
    EDAD NUMBER,
    CARRERA NVARCHAR2(50),
    SEMESTRE NUMBER,
    AÑO_INGRESO NUMBER,
    
    --VALORES VIEJOS :OLD
    NOMBRE_OLD NVARCHAR2(50),
    APELLIDO_OLD NVARCHAR2(50),
    EDAD_OLD NUMBER,
    CARRERA_OLD NVARCHAR2(50),
    SEMESTRE_OLD NUMBER,
    AÑO_INGRESO_OLD NUMBER,
    
    --CAMPOS DE CONTROL
    USUARIO NVARCHAR2(50),
    FECHA_NOW DATE,
    MOVIMIENTIO NVARCHAR2(50),
    CONSTRAINT BITACORA_E_PK PRIMARY KEY(ID_BITACORA_E)
);
DROP TABLE BITACORA_E;

--CREAR SU PROPIA SECUENCIA
CREATE SEQUENCE ID_BITACORA_E
START WITH 1 
MINVALUE 1
MAXVALUE 9999
NOCACHE
NOCYCLE;

SELECT ID_BITACORA_E.NEXTVAL FROM DUAL;

--CREAR EL TRIGGER MULTIPLE
CREATE OR REPLACE TRIGGER TR_MULTIPLE_ESTUDIANTE
AFTER INSERT OR UPDATE OR DELETE ON ESTUDIANTE
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(50);
    LV_FECHA DATE;
BEGIN
    --RECUPERAR UN ID, LA FECHA DEL SISTEMA Y EL USUARIO DEL SISTEMA
    --VAMOS A RECUPERAR UN ID VALIDO USANDO UNA SECUANCIA
    SELECT ID_BITACORA_E.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;
    
    --CONDICION POR CUAL ACCION OCURRIRA DE TIPO DML
    IF INSERTING THEN 
    INSERT INTO BITACORA_E(ID_BITACORA_E, ID_ESTUDIANTE, NOMBRE, APELLIDO, EDAD, CARRERA, SEMESTRE, AÑO_INGRESO, 
                        NOMBRE_OLD, APELLIDO_OLD, EDAD_OLD, CARRERA_OLD, SEMESTRE_OLD, AÑO_INGRESO_OLD, USUARIO, FECHA_NOW, MOVIMIENTIO)
    VALUES(LV_ID_BIT,:NEW.ID_ESTUDIANTE,:NEW.NOMBRE, :NEW.APELLIDO, :NEW.EDAD, :NEW.CARRERA, :NEW.SEMESTRE, :NEW.AÑO_INGRESO, 
                        NULL, NULL,0, NULL, 0, 0, LV_USUARIO, LV_FECHA, 'INSERT' );
            
    --DE LO CONTRARIO A ACTUALIZAR
    ELSIF UPDATING THEN
    INSERT INTO BITACORA_E(ID_BITACORA_E, ID_ESTUDIANTE, NOMBRE, APELLIDO, EDAD, CARRERA, SEMESTRE, AÑO_INGRESO, 
                        NOMBRE_OLD, APELLIDO_OLD, EDAD_OLD, CARRERA_OLD, SEMESTRE_OLD, AÑO_INGRESO_OLD, USUARIO, FECHA_NOW, MOVIMIENTIO)
    VALUES(LV_ID_BIT,:NEW.ID_ESTUDIANTE,:NEW.NOMBRE, :NEW.APELLIDO, :NEW.EDAD, :NEW.CARRERA, :NEW.SEMESTRE, :NEW.AÑO_INGRESO, 
                        :OLD.NOMBRE, :OLD.APELLIDO , :OLD.EDAD, :OLD.CARRERA, :OLD.SEMESTRE, :OLD.AÑO_INGRESO, LV_USUARIO, LV_FECHA, 'UPDATE' );
    
    --DE LO CONTRARIO A ELIMINAR
    ELSIF DELETING THEN
    INSERT INTO BITACORA_E(ID_BITACORA_E, ID_ESTUDIANTE, NOMBRE, APELLIDO, EDAD, CARRERA, SEMESTRE, AÑO_INGRESO, 
                        NOMBRE_OLD, APELLIDO_OLD, EDAD_OLD, CARRERA_OLD, SEMESTRE_OLD, AÑO_INGRESO_OLD, USUARIO, FECHA_NOW, MOVIMIENTIO)
    VALUES(LV_ID_BIT,:OLD.ID_ESTUDIANTE,NULL, NULL ,0, NULL , 0 , 0, 
                        :OLD.NOMBRE, :OLD.APELLIDO , :OLD.EDAD, :OLD.CARRERA, :OLD.SEMESTRE, :OLD.AÑO_INGRESO, LV_USUARIO, LV_FECHA, 'DELETE' );
    END IF;
            
END TR_MULTIPLE_ESTUDIANTE;
/

SELECT * FROM ESTUDIANTE;
SELECT * FROM BITACORA_E;

DROP TABLE BITACORA_E;

INSERT INTO ESTUDIANTE VALUES (2,'DANY', 'MARTINEZ', 20, 'ING.INDUSTRIAL', 5, 2020);
            
--ACTUALIZAMOS
UPDATE ESTUDIANTE SET 
    NOMBRE = 'JUAN'
WHERE ID_ESTUDIANTE = 2;

--ELIMINAMOS
DELETE ESTUDIANTE WHERE ID_ESTUDIANTE = 1;


