CREATE TABLE TIENDA(
    ID_TIENDA NUMBER GENERATED AS IDENTITY,
    CODIGO NVARCHAR2(50),
    NOMBRE NVARCHAR2(20),
    DIRECCION NVARCHAR2(50),
    TIPO NVARCHAR2(50),
    CIUDAD NVARCHAR2(50)
);

DROP TABLE TIENDA;

SELECT * FROM TIENDA;

SELECT * FROM CLIENTE;

SELECT *FROM DEPARTAMENTO;


