spring.application.name=EurekaServer

#Eureka es un administrador donde registra los servicios y sabe quien esta disponibles en cada momentos
server.port=8761

#Configuracion de Eureka Server donde se estara ejecutando la instancia
eureka.instance.hostname=localhost

#Configurcion de la url del servicio de Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Indica que esta instancia (el servidor) no se registra a si misma como cliente
eureka.client.register-with-eureka=false

#El cliente no debe de obtener registro de los demas microservicios
eureka.client.fetch-registry=false

#Valor por defecto y recomedable en produccion (evita que se dé de baja masivamente instancias ante fallos de red)
eureka.server.enable-self-preservation=true

#Exponer todos los endpoints que adminsitra Sprint Boot Actuator, Util en desarrollo, en produccion conviene limitarlo
management.endpoints.web.exposure.include=*

#Mostrar el detalle completo en la pagina de estado de salud de la aplaicacion
management.endpoint.health.show-details=always