spring.application.name=EurekaServer


#Eureka es un administrador donde registra los servicios y sabe quien esta disponible en cada momento

#Configuracion del puerto 
server.port=8761

#Configuracion del Eureka Server donde se estara ejecutando la instancia
eureka.instance.hostname=localhost

#Configuracion de la url del servicio Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Indicar que el cliente no debe registrarse al servidor Eureka
eureka.client.register-with-eureka=false

#El cliente no debe obtener el registro de los demas microservicios
eureka.client.fetch-registry=false

#Ayudar al servidor Eureka contra la perdida de demaciadas instancias o caso de red inestable
eureka.server.enable-self-preservation=true

#Exponer todos los endpoints que admonistran Spring Boot Actuator
management.endpoints.web.exposure.include=*

#Mostrar el detalle completo en la pagina de estado de salud de la aplicacion
management.endpoint.health.show-details=always