spring.application.name=EurekaServer


#Eureka es un administrador donde registra los servicios y sabe quien esta disponible en cada momento
#Configuracion del puerto 
server.port=8761
#Configuracion del Eureka Server donde se estara ejecutando la instancia
eureka.instance.hostname=localhost
#Configuracion de la url del servicio Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#Indica que ESTA instancia (el servidor) no se registra a sí misma como cliente.
eureka.client.register-with-eureka=false
#El cliente no debe obtener el registro de los demas microservicios
eureka.client.fetch-registry=false
#Valor por defecto y recomendable en producción (evita que se dé de baja masivamente instancias ante fallos de red)
eureka.server.enable-self-preservation=true
#Exponer todos los endpoints que admonistran Spring Boot Actuator, Útil en desarrollo; en producción conviene limitarlo.
management.endpoints.web.exposure.include=*
#Mostrar el detalle completo en la pagina de estado de salud de la aplicacion
management.endpoint.health.show-details=always