spring.application.name=Producto

#Las bases de datos H2 o base de datos embebidas, son bases que nos ofrese Spring Boot para hacer pruebas
#son bases de datos en memoria, es decir que no se guardan en un archivo fisico, simulan una base de datos real
#Y esto sin hacer ninguna configuracion adicional

server.port=8002

#Base de datos H2
#Indicamos que sera todo en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
